apps/tup-ui/src/App.spec.tsx
Fix a test failure in isolation from other PRs.
_This was caught by code coverage check in workflow. It blocked https://github.com/TACC/tup-ui/pull/2._
=> fix(tup-ui): app default test case failure

apps/tup-ui/src/App.spec.tsx, apps/tup-ui/src/App.tsx, apps/tup-ui/src/auth/LoginComponent.spec.tsx, apps/tup-ui/src/auth/LoginComponent.tsx, apps/tup-ui/src/auth/ProfileComponent.tsx, apps/tup-ui/src/hooks/useJwt.spec.tsx, apps/tup-ui/src/main.tsx, apps/tup-ui/src/utils.tsx, package-lock.json, package.json
Integrate react-router into the TUP-UI auth flow implementing the following:
- Nested routes utilizing layout components with outlets.
- Protected routes that redirect to login if the user is not authenticated.
- Tests that accurately model the redirect behavior.
- [TUP-312](https://jira.tacc.utexas.edu/browse/TUP-312)
1. Clear cookies and visit the home page at localhost:3000. you should be redirected to the `/login` route. 
2. Enter your credentials and check that you are redirected back to `/`
3. Refresh the page and check that you still see your profile and aren't redirected.
=> task/TUP-312: Add routing to auth flow

libs/core-styles/src/lib/_imports/trumps/s-header.css, libs/core-styles/src/lib/_tests.css
Fix miscellaneous inaccuracies in docs and comments since recent updates.
- https://github.com/TACC/Core-CMS/pull/525
- mimicked by https://github.com/TACC/Core-Styles/pull/38
N/A
=> chore(core-styles): update docs & comments

apps/tup-cms/Dockerfile
Get latest relevant Core CMS image.
<sup>Build: https://jenkins01.tacc.utexas.edu/job/Core_CMS_Build/835</sup>
- [FP-1854](https://jira.tacc.utexas.edu/browse/FP-1854)
- [TUP-340](https://jira.tacc.utexas.edu/browse/TUP-340)
See:
- https://github.com/TACC/tup-ui/pull/53
- https://github.com/TACC/tup-ui/pull/58#discussion_r1001236215
=> feat(tup-cms): get CMS image of recent-merged fp-1854 + tup-340

package-lock.json, package.json
=> Bump vite to v3.2.2

apps/tup-ui/src/main.global.css, libs/tup-components/src/layout/PageLayout/PageLayout.module.css, libs/tup-components/src/layout/PageLayout/PageLayout.tsx, libs/tup-components/src/layout/Sidebar/Sidebar.module.css
Refactor `PageLayout` to use the CSS grid. There should be no visual changes/regressions.
=> Refactor PageLayout to use CSS grid

apps/tup-cms/Dockerfile, apps/tup-cms/src/apps/dashboard/templates/dashboard/assets.html, apps/tup-ui/src/main.global.css, apps/tup-ui/src/pages/Login/Login.module.css, libs/core-components/src/lib/SectionHeader/SectionHeader.jsx, libs/core-components/src/lib/SectionHeader/SectionHeader.module.css, libs/core-components/src/lib/SectionHeader/SectionHeader.test.js, libs/tup-components/src/auth/LoginComponent/LoginComponent.module.css, package-lock.json, package.json
1. Load Portal heading reset & new font size vars from Core-Styles (via CMS which also includes demo of them).
2. Style Portal headings to match design.
3. Update Login form styles to adapt to mix of Portal and CMS styles.[^1]
- includes #87
- requires https://github.com/TACC/Core-Styles/pull/90
- newer cms image
- style headings
- fix unsurprising new bugs in login form
- newer core-styles
1. Verify the big and small headings match [design](https://xd.adobe.com/view/cc3dc245-2792-4e10-bdc1-50d2a7d32979-996e/screen/b1728cf1-1c38-45d1-91c3-560b803632cd/specs/).
2. Verify the login page is unchanged.*
<sup>* Except for the font size bug fix[^2].</sup>
| Dashboard (scroll up) | Dashboard (scroll down) | Projects |
| - | - | - |
| ![Dashboard - …
=> feat(tup-ui): new font sizes

apps/tup-cms/Dockerfile, package-lock.json, package.json
Downstream regression test of https://github.com/TACC/Core-Styles/pull/102.
- https://github.com/TACC/Core-Styles/pull/102
=> feat(core-styles): base, cms, docs, portal re-org

apps/tup-ui/src/pages/Dashboard/Dashboard.module.css, apps/tup-ui/src/pages/Dashboard/Dashboard.tsx
Small tweaks to keep the grid in line with the mockups.
=> Dashboard grid css tweaks

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/projects/users/UserDetail/UserDetail.tsx, libs/tup-components/src/projects/users/UserList/ManageTeam.tsx, libs/tup-components/src/projects/users/UserList/UserList.module.css, libs/tup-hooks/src/index.ts, libs/tup-hooks/src/useProjectUsers.ts, libs/tup-hooks/src/useProjects.ts
Adds hooks for adding/removing users, and setting/unsetting project delegates.
=> Add hooks and integration for adding/removing users and delegates

apps/tup-ui/src/main.tsx, apps/tup-ui/src/utils.tsx, libs/tup-hooks/src/index.ts, libs/tup-hooks/src/requests.spec.tsx, libs/tup-hooks/src/requests.ts, libs/tup-hooks/src/useAuth.ts, libs/tup-hooks/src/useGrants.ts, libs/tup-hooks/src/useJwt.ts, libs/tup-hooks/src/useMfa.tsx, libs/tup-hooks/src/useProfile.ts, libs/tup-hooks/src/useProjectScienceField.ts, libs/tup-hooks/src/useProjectUsage.ts, libs/tup-hooks/src/useProjectUsers.ts, libs/tup-hooks/src/useProjects.ts, libs/tup-hooks/src/usePublications.ts, libs/tup-hooks/src/useSystemMonitor.ts, libs/tup-hooks/src/useTickets.ts, libs/tup-hooks/src/useUserNews.tsx, libs/tup-testing/src/utils.tsx, package-lock.json, package.json
React-query has a new maintance model/doc site so we should update our dependency before people get confused.
=> Update react-query to tanstack-query

libs/tup-components/src/projects/details/ProjectEdit/ProjectEditForm.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantCreateForm.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationCreateForm.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationEditForm.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationForm.module.css, libs/tup-components/src/projects/details/publications/ProjectPublicationFormFIelds.tsx
- Fix "TAC Resources" typo
- Fix "Field of Science" validation in Edit Projects (needs to be >1, not just truthy)
- Fix CSS bug where Publication Add form was overflowing the modal
- [TUP-410](https://jira.tacc.utexas.edu/browse/TUP-410)
=> task/TUP-410: Small fixes for Projects forms

libs/tup-components/src/projects/details/ProjectDetails.tsx
Allow the user to add a new allocation and to request an increase to an existing allocation. To add a new allocation, the user is sent to the TxRAS home page(Start New Submission). To increase allocation amount to an existing allocation, the user is sent to the My Allocation Request page of TxRAS.
- [TUP-411](https://jira.tacc.utexas.edu/browse/TUP-411)
On the project details page, two new links were added next to Allocations: 
+ Add New Allocation --> redirects to TxRAS home page (Start New Submission) --> https://submit-tacc.xras.org/
Increase Existing Allocation --> redirects to TxRas My Allocation Request page --> https://submit-tacc.xras.org/requests
1. In the Nav bar, select Projects & Allocations
2. Select a project that you are a PI or delegate for
3. Click the links next to …
=> tup-411-txras-allocations-link

libs/tup-components/src/projects/header/ProjectHeader/ProjectHeader.tsx, libs/tup-components/src/projects/users/UserList/ManageTeam.tsx
Update the compute/storage calculations to include all active allocations.
- [TUP-403](https://jira.tacc.utexas.edu/browse/TUP-403)
1. Go to a project under Active Projects and check that the Compute values in the header match the sum of values in the allocations table and are rounded to 1 decimal place.
=> task/TUP-403: Update compute/storage in project header to match allocations table.

apps/tup-cms/Dockerfile
Small neglected improvements to Core-CMS news.
N/A
<details><summary>"To be published" vs. "Published"</summary>
1. Create/Find article that is **not** published **but** has publish date.
2. Verify article shows "To be published [DATE]" not "Published [DATE]".
3. Create/Find article that is published **and** has publish date.
4. Verify article shows "Published [DATE]" not "To be published [DATE]".
</details>
<details><summary>Do <strong>not</strong> stretch article link over article.</summary>
0. Do **not** be in Edit mode.
1. View list of articles.
2. Verify article link is the header, not the entire article.
</details>
<details><summary><strong>Do</strong> stretch article link over article image.</summary>
1. View list of articles.
2. Verify article image is a a link to the article. …
=> feat(tup-cms): core-cms news tweaks

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx, libs/tup-components/src/projects/ProjectLayout.test.tsx, libs/tup-components/src/projects/details/ProjectEdit/ProjectEditForm.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantCreateForm.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantEditForm.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantFormFields.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationEditForm.tsx, libs/tup-components/src/system_monitor/SystemMonitor.test.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.test.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.test.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.tsx, libs/tup-components/src/tickets/TicketsCells.tsx
Fix PR annotations about unused code.
- found on https://github.com/TACC/tup-ui/pull/154/files
- remove unused code
1. This PR should have zero automatic annotations about unused code.
N/A
=> chore(tup-components): pr auto annotations

apps/tup-cms/src/apps/portal/views.py
Redirect to /login on logout
- [TUP-428](https://jira.tacc.utexas.edu/browse/TUP-428)
1. From an authenticated view, click "log out".
2. Confirm that you are redirected to the login page.
=> task/TUP-428: Redirect to /login on logout

apps/tup-ui/src/pages/Projects/Projects.tsx
Add TXRAS link to main Projects listing
- [TUP-426](https://jira.tacc.utexas.edu/browse/TUP-426)
On the Projects & Allocations page, added a "+ New Project" button that links to https://submit-tacc.xras.org/
1. Navigate to Projects & Allocations, confirm "+ New Project" button is there and the link works correctly. 
I'm not sure if the link is going to the correct place. 
The button is aligned far to the right, need help moving it slightly left.
=> Tup 425 add txras link

apps/tup-cms/Dockerfile, package-lock.json, package.json
Update Core-Styles to get fix for button color on dark sections.
- installs https://github.com/TACC/Core-Styles/pull/137
- new cms image
- new core-styles version
1. Open homepage.
2. Scroll to a dark section of the page.
3. Verify the button is light purple, not vivd purple.
...
=> fix(core-styles): button light/dark bug (and new core-styles dev features)

apps/tup-cms/src/taccsite_cms/templates/snippets/component-software-table.html, apps/tup-cms/src/taccsite_cms/templates/snippets/component-system-monitor.html
Improve markup in CMS snippets that load tup-cms-react components.
N/A
- load styles first
- use consistent IDs
- add `tup-cms-react` class
N/A
=> chore(tup-cms): tup-cms-react, minor snippet update

apps/tup-cms/src/taccsite_cms/settings_custom.py
1. Remove duplicate setting.
2. Move a few settings to location consistent with Core-CMS.
None.
- move to expected location
- do not repeat INCLUDES_SEARCH_BAR
- set INCLUDES_SEARCH_BAR to True
N/A
<sup>Recent changes to values in server secrets file overwrite the functional change here anyway.</sup>
=> chore(tup-cms): noop, portal and search settings

apps/tup-cms/src/taccsite_cms/settings_custom.py
Add GA4 property ID to custom settings.
=> conf: Add GA4 property ID to settings

libs/tup-components/src/projects/users/UserList/AddUserModal.module.css, libs/tup-components/src/projects/users/UserList/AddUserModal.tsx, libs/tup-components/src/projects/users/UserList/UserList.module.css
Resolve issues form design reviews.
- updates #246
- **fixed** modal height from dynamic to static
- **fixed** modal scroll to be on the table
- **feat**: right-align add/remove column
- **fix**: shrink-wrap add/remove column
1. Open a project of which you are a PI or manager.
2. Open the "Add Users" (via the [+ Add Users] button).
3. Check bottom of modal does not have a stray border (from empty footer).
4. Search for a user that gives results, like Last Name: "Gonzalez".
5. Check modal height does not change.
6. Make browser window vertically short enough that it cannot fit all rows in table.
7. Check modal height changes (to remain 50% height of browser window).
8. Check table has a scrollbar.
9. Scroll the table.
10. Check table header does not scroll away.
11. Add a user.
12. Check …
=> Search modal for adding members to projects - UI tweaks

libs/tup-components/src/projects/details/ProjectDetails.tsx
Update wording on Projects
- [TUP-478](https://jira.tacc.utexas.edu/browse/TUP-478)
The statement: “Your project and allocation information can be managed on the TXRAS portal"
has changed to: “Your project and allocation information can be managed on the TXRAS or ACCESS portals."
1. Go to http://localhost:8000/portal/dashboard
2. Click on a project title
3. At the bottom of the project page, the new text should appear italicized.
=> TUP-478-Update-wording-on-projects

apps/tup-cms/src/apps/portal/apps.py, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx, libs/tup-components/src/tickets/index.ts
Add the following queue mappings: 
Allocations > Allocations Queue 
Login Issues > Accounts Queue 
MFA Issues > MFA Queue 
Running Jobs or Using TACC Resources > HPC Queue 
- [TUP-533](https://jira.tacc.utexas.edu/browse/TUP-533)
=> task/TUP-533: Update queue selection for tickets

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
User services requested that these categories be removed.
- [TUP-539](https://jira.tacc.utexas.edu/browse/TUP-539)
=> task/TUP-539: Remove Data Analytics and Security options from ticket categories

apps/tup-cms/src/apps/portal/apps.py, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx, libs/tup-components/src/tickets/index.ts
Add "Arecibo Data" to ticket categories, pointing to the High Performance Computing queue.
- [TUP-539](https://jira.tacc.utexas.edu/browse/TUP-539)
=> task/TUP-539: Add "Arecibo Data" to ticket categories

apps/tup-ui/src/styles/README.md
Add "Bootstrap" section to TUP UI `styles/README.md`.
N/A
1. [Preview.](https://github.com/TACC/tup-ui/blob/docs/limit-use-of-bootstrap/apps/tup-ui/src/styles/README.md)
2. In "Table of Contents", click "Limit Use of Bootstrap".
3. Test links.
=> docs: limit use of bootstrap

apps/tup-cms/src/taccsite_cms/templates/snippets/css-news-hacks.html
Save new CSS—whose future is undecided—to a snippet.
- quick fix until design completes [TUP-552](https://jira.tacc.utexas.edu/browse/TUP-552)
1. Open https://dev.tup.tacc.utexas.edu/news/latest-news/.
2. Verify no "by: " text before an author's name.
3. Verify code used is from [snippet](https://dev.tup.tacc.utexas.edu/admin/djangocms_snippet/snippet/132/change/).
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/f793e687-d3ef-4b9f-a75c-bd3ad0949adf) | ![after](https://github.com/TACC/tup-ui/assets/62723358/997361c1-8196-423e-a854-da850d279664) |
=> chore: save quick fix to hide "by:" text in by line

libs/tup-components/src/projects/details/ProjectDetails.test.tsx, libs/tup-components/src/projects/details/ProjectDetails.tsx
Update the blurb under the project description to be more clear about where users should go to manage projects (request from User Services).
- [TUP-562](https://jira.tacc.utexas.edu/browse/TUP-562)
=> Update wording of blurb under Project Details

apps/tup-ui/src/styles/README.md
Fix a bad link.
- fixes #289
1. View document at https://github.com/TACC/tup-ui/blob/docs/bad-link-in-new-doc-content/apps/tup-ui/src/styles/README.md.
2. Verify links work.
Skipped.
=> fix: bad link in newly merged doc tweak

apps/tup-ui/src/pages/Dashboard/Dashboard.module.css, libs/tup-components/src/news/UserNews.tsx, libs/tup-components/src/projects/ProjectsTable.tsx, libs/tup-components/src/tickets/TicketsDashboard.module.css, libs/tup-components/src/tickets/TicketsDashboard.tsx, libs/tup-components/src/tickets/TicketsTable.tsx
=> Revert "feat: tup-414 help users "View all …""

libs/tup-components/src/projects/users/UserList/AddUserModal.module.css, libs/tup-components/src/projects/users/UserList/AddUserModal.test.tsx, libs/tup-components/src/projects/users/UserList/AddUserModal.tsx, libs/tup-components/src/projects/users/UserList/ManageTeam.tsx
This reverts commit e0268e3fa8e7091d693230d5bd6164279d8ad8ea.
1.
=> Revert "replace Manage Team modal with link to TAM invitation page

libs/tup-components/src/accounts/ManageAccount.module.css
Reduce size of icon in My Account section header.
<sub>Also, remove horizontal padding that is not in the [design](https://xd.adobe.com/view/cc3dc245-2792-4e10-bdc1-50d2a7d32979-996e/).</sub>
- **removed** horizontal padding
- **changed** icon styles
1. Open http://localhost:8000/portal/account.
2. Verify user icon in header is smaller and vertically-centered-ish with header text.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/25ead2a5-2f0c-4a3b-b865-05a827e03478) | ![after](https://github.com/TACC/tup-ui/assets/62723358/cf568c1c-ae2c-460c-a584-c1ac834b7e05) |
=> feat: add link in Dashboard to "View all tickets"

apps/tup-ui/src/main.global.css
Remove temporary Core-Styles imports, because CMS's `core-styles.portal.css` has newer version.
<details>
- Some Core-Styles were loaded via CDN, cuz CMS did not have latest yet.
- Now CMS has much more recent Core-Styles, so use them. Do not duplicate.
</details>
- [TUP-463](https://jira.tacc.utexas.edu/browse/TUP-463)
- **removed** temporary Core-Styles imports
1. `c-nav`:
1. Open MFA pairing or unpairing process.
2. The header links at the top-right should match prod.
3. There should be no duplicate CSS.
2. `c-form`:
1. Open all forms.
2. The form styles should match prod.
3. There should be no duplicate CSS.
3. `s-affixed-input-wrapper`:
1. Open MA pairing process.
2. Click to generate QR code.
3. The styles for alt. text code to copy should match prod.
3. There should be no duplicate …
=> chore: tup-463 remove temp. core-styles imports

.github/pull_request_template.md
JIRA URL has changed, so update that. And 1234 could be skipped, because numbers are expected, while XYZ is obviously wrong, so use XYZ to better suggest change.
Other repos have had their templates updated.
- **changed** pull_request_template JIRA ticket sample URL
N/A
=> docs: update URL for sample JIRA task

apps/tup-cms/Dockerfile
Get CMS image with:
- https://github.com/TACC/Core-CMS/pull/788
- [TUP-681](https://tacc-main.atlassian.net/browse/TUP-681)
https://github.com/TACC/tup-ui/assets/62723358/2811b248-d624-49e8-9d5f-abd620f51931
=> feat: tup-681 cms image that can turn off drop cap

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
Add Stampede3 to help ticket dropdown.
- [TUP-699](https://tacc-main.atlassian.net/browse/TUP-699)
- **added** one new `<option>`
1. Login to Portal.
2. Create a new ticket (from Dashboard or Tickets sections).
3. Choose "Stampede3(…)" from the list.
4. Send ticket.
5. Open ticket.
6. Verify System/Resource is "Stampede3(…)".
=> feat: TUP-699 add Stampede3 to help ticket opts

apps/tup-cms/Dockerfile
Update to [Core-CMS v4.10.2](https://github.com/TACC/Core-CMS/releases/tag/v4.10.2).
> [!IMPORTANT]
> Deployed to [TUP Dev](https://dev.tup.tacc.utexas.edu/) via [v1.1.9-202404-02](https://github.com/TACC/tup-ui/compare/v1.1.8-202404-01...v1.1.9-202404-02) / #451 at 4f89e3f which is merely [two release maintenance commits](https://github.com/TACC/tup-ui/assets/62723358/a08bed0a-8955-4094-9e93-1ec377df652f) behind [v4.10.2](https://github.com/TACC/Core-CMS/releases/tag/v4.10.2).
- ~~[CMD-72](https://tacc-main.atlassian.net/browse/CMD-72): All CMS Forms Should Send Confirmation E-Mail~~
- [CMD-107](https://tacc-main.atlassian.net/browse/CMD-107): News Feed Main Page Uses Page Title
- [CMD-112](https://tacc-main.atlassian.net/browse/CMD-112): Let Client CMS Overwrite Core-CMS Confirmation …
=> feat: core-cms v4.10

apps/tup-cms/src/apps/portal/apps.py
New wording:
Greetings,
Thank you for reaching out to TACC and completing the FORM NAME.
- For training registration requests, you will be contacted within one week to confirm registration. For additional help please contact Lauren Bruce ([lbruce@tacc.utexas.edu](mailto:lbruce@tacc.utexas.edu)).
- For tour requests, a tour coordinator will contact you within two business days to complete your reservation. For additional assistance please reach out to [info@tacc.utexas.edu](mailto:info@tacc.utexas.edu).
- For all other issues, a TACC support person will be in contact shortly. For additional assistance please reach out to [info@tacc.utexas.edu](mailto:info@tacc.utexas.edu).
Thank you for your time,
TACC Support
=> Update wording on confirmation email

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Replace dead CMS link with TAM page.
=> Fix link to TAM registration page

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
=> Quick: Update ticket options to remove"Agave" terminology

libs/tup-components/src/projects/details/ProjectDetails.tsx
Perform request to XRAS link for "Increase Existing Allocation".
- [internal Slack request](https://tacc-team.slack.com/archives/CKB616RB8/p1730310533044809)
- **changed** one possible URL of a dynamic link
1. Be logged in with "`chargeCode` that starts with `TG-`".
2. Verify link Increase Existing Allocation goes to https://submit-tacc.xras.org/requests.
Skipped.
=> enhance: new link to "Increase Existing Allocation"

libs/tup-components/src/mfa/Mfa.module.css, libs/tup-components/src/mfa/MfaUnpairingView.tsx
Increase font size of the unpairing message.
=> Quick: Increase MFA unpairing message font size

libs/tup-components/src/projects/users/UserList/UserList.module.css, libs/tup-components/src/projects/users/UserList/UserList.tsx
Sort usernames on allocation by last name
- [WP-826](https://tacc-main.atlassian.net/browse/WP-826)
- Sorts usernames 
- Styling changes
1. Go to [http://localhost:8000/portal/projects/](http://localhost:8000/portal/projects/) and select a project
2. Check that the usernames are listed alphabetically by last name
3. Check against styles shown in the Jira task
=> WP-826 Updating allocation names showing in TUP

apps/tup-cms/src/taccsite_cms/templates/snippets/css-navbar-width-horz-scrollbar.html
Save fixes to snippet that avoids horizontal scrollbar.
- borrows early from [TACC/Core-CMS@v4.25.1](https://github.com/TACC/Core-CMS/releases/v4.25.1)
- updates made after release since #499
- **saves** changes already made in snippet:
- fix: Threads "@" social media link in footer causes horz. scrollbar
- fix: first link of CMS nav not quite aligned with "Dashboard" heading
- fix: inconsistent header font (fixed the right way in Core-CMS v4.25.1)
N/A
Just version-tracking snippet code.
=> chore: continue to avoid horizontal scrollbar

libs/tup-components/src/accounts/ManageAccount.tsx
Remove MFA and replace with link to TAM page
=> TAM: Remove MFA and replace with link to TAM page

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.test.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
=> fix: inconsistent help/ticket form dropdown opts
