TACC/tup-ui

.github/workflows/main.yml, apps/tup-ui/src/index.css, apps/tup-ui/vite.config.ts
Configure tup-ui to load styles from the correct path.
- caused by https://github.com/TACC/tup-ui/pull/2
- changed root path for `@tacc/core-styles` import
- changed bad paths for tup-ui CSS imports
1. Build core-styles i.e. `npx nx build core-styles`.
2. Serve tup-ui i.e. `npx nx serve tup-ui`.
3. Verify app loads without error.
4. Pipeline should have zero errors.
This was committed directly to branch [task/tup-272-core-components](https://github.com/TACC/tup-ui/tree/task/tup-272-core-components) to fix the problem so we could make progress on that branch.
=> fix(tup-ui): load CSS from correct path

libs/core-styles/src/lib/_imports/settings/color.css
Add new color that:
- CMS forms will use
- fits among existing global colors
- [TUP-308](https://jira.tacc.utexas.edu/browse/TUP-308)
- required by https://github.com/TACC/Core-CMS/pull/498
https://github.com/TACC/Core-CMS/pull/498
The original plan to make this change came from [TACC/Core-CMS#501](https://github.com/TACC/Core-CMS/pull/501/files#diff-e9414234ff809b486ac95af5c2c1b4fd1cf2dd7618564c667529baa52133d99fR68-R69), and it will be used in https://github.com/TACC/Core-CMS/pull/498.
Released in [@tacc/core-styles@0.7.0-beta](https://www.npmjs.com/package/@tacc/core-styles/v/0.7.0-beta) via [core-styles/v0.7.0-beta](https://github.com/TACC/tup-ui/compare/core-styles/v0.7.0-beta).
=> feat(core-styles): tup-308, new global color

libs/core-styles/.npmrc, libs/core-styles/CHANGELOG.md, libs/core-styles/README.md, libs/core-styles/package-lock.json, libs/core-styles/package.json, libs/core-styles/src/lib/_imports/objects/o-section.css, libs/core-styles/src/lib/_imports/settings/color.css
`@tacc/core-styles@0.7.0`
- fix [CMS v3.7.11](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=274530310) bad bug (see red row)
- new color var to support [TACC/Core-CMS#498](https://github.com/TACC/Core-CMS/pull/498)
- [FP-1723](https://jira.tacc.utexas.edu/browse/TUP-1723) via https://github.com/TACC/tup-ui/pull/29
- [TUP-308](https://jira.tacc.utexas.edu/browse/TUP-308) via https://github.com/TACC/tup-ui/pull/25
- published [@tacc/core-styles v0.7.0-beta](https://www.npmjs.com/package/@tacc/core-styles/v/0.7.0-beta) at https://github.com/TACC/tup-ui/pull/31
- published [@tacc/core-styles v0.7.0](https://www.npmjs.com/package/@tacc/core-styles/v/0.7.0) at e0bfb5e
=> Core styles/v0.7.0

libs/core-styles/.prettierignore
Remove a `.prettierignore` (in core-styles) because it has no effect.
_The root `.prettierignore` does the job._
N/A
- delete `libs/core-styles/.prettierignore`
N/A
=> fix(core-styles): drop ineffectual prettierignore

apps/tup-cms/README.md
Try to fix workflow error.
N/A
- remove extra space in a doc
N/A
=> fix(tup-cms): remove extra space from readme.md

apps/tup-cms/Dockerfile
Fix CMS bug adding plugin within a Text plugin.
- [FP-1949](https://jira.tacc.utexas.edu/browse/FP-1949)
- relies on https://github.com/TACC/Core-CMS/pull/573
- changed CMS image
Deployed to https://dev.tup.tacc.utexas.edu/ (2022-12-09).
For details, see https://github.com/TACC/Core-CMS/pull/573.
My tup-cms local test:
=> fix(tup-cms): full-height edit plugin inside text

apps/tup-cms/Dockerfile
Change CMS editor limitation so that we can create markup with _inline_ elements **not** wrapped by a `<p>` tag.
- most pattern markup work on CMS that started last week and will continue for weeks
- relies on https://github.com/TACC/Core-CMS/pull/574
- changed CMS image
See https://github.com/TACC/Core-CMS/pull/574.
Of the screenshots below, the WYSIWYG edit ones show the current tag at the bottom left e.g. "body > p":
| Manual Test | Screenshot |
| - | - |
| 1. **no** `<p>` added initially | <img width="983" alt="no p on initial entry" src="https://user-images.githubusercontent.com/62723358/207157603-a01f4d03-382d-4625-aaee-c6798eb5a515.png">
| 2. `<p>` added **after** pressing enter | <img width="983" alt="add p on press enter" …
=> fix(tup-cms): wysiwyg to not force <p> tag

apps/tup-cms/src/apps/dashboard/backend.py
Rewrite `localhost` to `host.docker.internal` when calling tup-services from inside of the local dev container.
=> Support tup-services running on localhost

apps/tup-cms/Dockerfile, package-lock.json, package.json
**1.** Hide text inside an `<i class="icon…">accessible text</i>`.
<sup>Also lets us prevent CMS from stripping empty tag from WYSIWYG.</sup>
- TACC/Core-Styles#86
- TACC/Core-Styles#88
**2.** Add an alias `.icon-collapse` for `.icon-contract`.
<sup>Because devs and I always expect the name to be `.icon-collapse`.</sup>
- TACC/Core-Styles#85
**3.** Fix a side effect from https://github.com/TACC/Core-CMS/pull/573.
<sup>Another editor window had become illegible.</sup>
- TACC/Core-CMS#575
| Source | Render |
| - | - |
| ![icon overflow - source](https://user-images.githubusercontent.com/62723358/207415701-675de200-0a71-4d1b-9438-dd26543ab7dd.png) | ![icon overflow - render](https://user-images.githubusercontent.com/62723358/207415700-6881c620-7837-4752-92ec-fa128af2981b.png)
| Source | …
=> chore(core-styles/cms): three small fixes/features

apps/tup-ui/src/pages/ProjectView/ProjectMember/ProjectMember.tsx, apps/tup-ui/src/pages/ProjectView/ProjectView.tsx, libs/core-wrappers/src/lib/Navbar/Navbar.module.css, libs/core-wrappers/src/lib/Navbar/Navbar.tsx, libs/tup-components/src/projects/index.ts, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/projects/users/UserDetail/UserDetail.tsx, libs/tup-components/src/projects/users/UserDetail/index.ts, libs/tup-components/src/projects/users/UserDetail/userDetail.spec.tsx, libs/tup-components/src/projects/users/UserList/UserList.module.css, libs/tup-components/src/projects/users/UserList/UserList.spec.tsx, libs/tup-components/src/projects/users/UserList/UserList.tsx, libs/tup-components/src/projects/users/UserList/index.ts, libs/tup-hooks/src/index.ts, libs/tup-hooks/src/useProjectUsage.ts, libs/tup-hooks/src/useProjectUsers.ts, libs/tup-testing/src/mocks/fixtures/index.ts, libs/tup-testing/src/mocks/fixtures/projects.ts, libs/tup-testing/src/mocks/handlers.ts
Add user list sidebar and user detail view (read-only for now, role selection and user removal will be implemented in separate PRs).
- [TUP-377](https://jira.tacc.utexas.edu/browse/TUP-377)
- Add a user list sidebar as part of the project view layout (visible in both project and user detail views).
- Add a user detail view with name/username/email and usage per allocation.
1. Navigate to `http://localhost:8000/dashboard/projects/{projectId}` where `projectId` is a project you have access to. check that the user sidebar displays and doesn't overflow beyond the page boundary.
2. Click on a username in the sidebar. Confirm that the detail view displays with the correct name/username/email. Confirm that the usage numbers in the table look reasonable.
=> task/TUP-377: Add project user list/detail view

apps/tup-cms/Dockerfile, apps/tup-ui/src/pages/Login/Login.module.css, libs/tup-components/src/auth/LoginComponent/LoginComponent.module.css, package-lock.json, package.json
Retrieve and adapt to new Core-Styles and Core-CMS font sizes... except headings.*
<sup>* Heading sizes are solved in https://github.com/TACC/tup-ui/pull/88.</sup>
</details>
- https://github.com/TACC/Core-Styles/pull/90
- recreates #87
- TACC/Core-CMS@d8080a9
- TACC/Core-CMS@08237ce
- new CMS image
- adapt font sizing of login page
<sup>which is running atop CMS styles (see "Notes" for details)</sup>
- install relevant TACC/Core-Styles
1. Verify Login font sizes match [design](https://xd.adobe.com/view/5d4860e3-cdbc-4e17-ab11-c411437e31c7-081b/specs/).
| - | - |
| <img width="733" alt="tup login form - top BEFORE" src="https://user-images.githubusercontent.com/62723358/207706539-5c5fb44e-ce0f-4c35-8582-8cdb7f7f4c13.png"> | <img width="733" alt="tup login form - top" …
=> feat(core-cms): new font sizes

apps/tup-cms/Dockerfile, apps/tup-cms/src/apps/dashboard/templates/dashboard/assets.html, apps/tup-ui/src/main.global.css, apps/tup-ui/src/pages/Login/Login.module.css, libs/core-components/src/lib/SectionHeader/SectionHeader.jsx, libs/core-components/src/lib/SectionHeader/SectionHeader.module.css, libs/core-components/src/lib/SectionHeader/SectionHeader.test.js, libs/tup-components/src/auth/LoginComponent/LoginComponent.module.css, package-lock.json, package.json
1. Load font variables and un-styled* headings from Core-Styles and new CMS image.
<sup>* Technically, Bootstrap has styled them, but please do not remind me. I fantasize I am not building atop Bootstrap.</sup>
3. Style headings on CMS and Portal.
- requires https://github.com/TACC/Core-Styles/pull/90
- includes #91
- includes #88
- required by #90
- changed https://github.com/TACC/Core-CMS image
- added `core-styles.portal.css` load
- added styles for headings
- changed `<Section…>` components to use `<h1>` and `<h2>`
- changed `<Section…>` components to use simpler CSS
- changed https://github.com/TACC/Core-Styles commit
[Deployed to dev.tup on 2022-12-20.](https://tacc-team.slack.com/archives/C02GF2X2AS3/p1671571908970539)
Except for "Email or" of "Email or User Name" and "User " or …
=> feat: new font sizes - cms & portal

.github/workflows/main.yml
Use the setup-node action to reduce runtime for actions. Our current caching setup doesn't seem to cache npm modules correctly.
=> Update Github Actions to improve npm caching

apps/tup-ui/src/main.global.for-core-styles.css, apps/tup-ui/src/main.tsx, apps/tup-ui/src/pages/Projects/Projects.module.css, libs/core-components/src/lib/Icon/Icon.tsx, libs/core-wrappers/src/lib/Navbar/Navbar.tsx, libs/tup-components/src/layout/PageLayout/PageLayout.module.css, libs/tup-components/src/projects/ProjectsListing/ProjectSummary.tsx, libs/tup-components/src/projects/ProjectsListing/ProjectsListing.module.css, libs/tup-components/src/projects/ProjectsListing/ProjectsListing.test.tsx, libs/tup-components/src/projects/ProjectsListing/ProjectsListing.tsx
CSS: Tweak page layout spacing. Use global variables. Larger nav icons. Global CSS for Core-Styles.
- https://github.com/TACC/tup-ui/pull/101
- feat(core-components): Icon, add size prop d3e45ca
- feat(tup-ui): global css destined for core-styles 6c21c94
- fix(core-wrappers): nav icon size 4bc1ed8
- fix(tup-ui): page layout spacing & use global vars bdf20fe
- fix(tup-ui): ProjectSummary markup clean up 9777ea3
See https://github.com/TACC/tup-ui/pull/101.
| scroll to top | scroll to bottom |
| - | - |
| ![Screen Shot 2023-01-18 at 15 16 23](https://user-images.githubusercontent.com/62723358/213296544-58b0b0f0-abaa-44ed-b61b-33d0dd4598d3.png) | ![Screen Shot 2023-01-18 at 15 16 26](https://user-images.githubusercontent.com/62723358/213296540-2556f3b1-4b5a-4e70-84e7-e320511ba2ab.png) |
=> fix(tup-ui): page layout spacing, icon size, use global vars, core-styles patches

apps/tup-cms/docker-compose.dev.yml
- https://github.com/TACC/Core-CMS/pull/579
=> feat(tup-cms): fp-1952 isolate ES network

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.test.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.test.tsx
Some tests might be flaking out because they're firing a click event on an inactive input.
=> Blur inputs in Formik tests to ensure buttons are active

apps/tup-cms/src/taccsite_cms/settings_custom.py
- Install News plugin.
- Add CMD News.
- Draft styles for Multimedia articles.
- [**TUP-118**](https://jira.tacc.utexas.edu/browse/TUP-118) ([TUP-258](https://jira.tacc.utexas.edu/browse/TUP-258))
- requires https://github.com/TACC/Core-CMS/pull/572
ⓘ Ignore the diff, because it became minimal as the base branch and this branch were synced.
- changed CMS image to one with newer News styles and fixes
- added settings to install News
- added URLs to support News
1. Open https://dev.tup.tacc.utexas.edu/news/latest-news/.
2. Play around.*
<sup>* [user guide](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=182911007), [admin guide](https://confluence.tacc.utexas.edu/pages/viewpage.action?pageId=276662476)</sup>
See:
- https://github.com/TACC/Core-CMS/pull/572
- …
=> feat(tup-cms): cmd news

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.test.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.test.tsx
Tests were flaking when `fireEvent` was used to update form text in tests, maybe due to a race condition.
=> Simulate user events when testing Formik components

apps/tup-cms/src/apps/dashboard/templates/dashboard/assets.html, apps/ui-patterns/src/main.css, libs/tup-components/src/auth/LoginComponent/LoginComponent.module.css
Remove CMS styles from Portal.
<details><summary>Why were they ever loaded at all?</summary>
Because, initially, TACC/Core-Styles had a `core-styles.base.css` and `core-styles.cms.css` and an **empty** `core-styles.portal.css`. The `core-styles.cms.css` had some stuff Portal needed, but also stuff it did **not** need. But now TACC/Core-Styles has a minimal, usable `core-styles.portal.css`.
</details>
<details><summary>I took some actions in CMS to support these changes once deployed.</summary>
The CMS uses snippets for a lot of new code (because we are developing too fast for me to develop all new CSS in Core-CMS or Core-Styles. Some of those snippets' styles used selectors that accidentally matched Portal markup. I have fixed those mistakes.
</details>
None.
- CMS Dashboard App:
- Do not …
=> fix(tup-ui): do not load core cms styles in portal

apps/tup-ui/src/pages/Dashboard/Dashboard.css, apps/tup-ui/src/pages/Dashboard/Dashboard.tsx
Limit dashboard body scroll solution to **only** screens that are _wide_ **and** _short_**.
- replaces #115
0. Load dashboard.
1. **If** you are a CMS admin, **then**—using "Inspect Element" tool—delete `margin-top: 46px` from `<html>`.
<sub>That style is added dynamically by CMS admin to make room for the CMS admin header/toolbar.</sub>
2. Verify scrollbar state at window sizes matches table data.
**At given size (w x h), is scroll(bar) required to see footer?**
| `px` | 1199– | 1200+ |
| - | - | - |
| 899– | **no** | **yes** |
| 900+ | **no** | **no** |
| `px` | 1199– | 1200+ |
| - | - | - |
| 899– | ![narrow short](https://user-images.githubusercontent.com/62723358/215183975-2a24257c-c57e-40ec-bbbd-bccfd8640d66.png) | ![wide short](https://user-images.githubusercontent.com/62723358/2151 …
=> fix(tup-ui): limit dashboard min height solution to wide & short screens

apps/tup-cms/src/apps/dashboard/urls.py, apps/tup-cms/src/apps/dashboard/views.py, apps/tup-ui/src/App.tsx, libs/core-wrappers/src/index.ts, libs/core-wrappers/src/lib/Navbar/Navbar.tsx, libs/core-wrappers/src/lib/Navbar/index.ts, libs/tup-components/src/layout/Sidebar/Sidebar.tsx
Prevent the situation where clicking "Log Out' would redirect to the dashboard but still display a logged-in state in the navbar and let CMS users continue to edit. 
- [TUP-404](https://jira.tacc.utexas.edu/browse/TUP-404)
Replace the client-side logout with a server-side route that kills the user's Django session and unsets their x-tup-token cookie.
1. From the dashboard, click "Log Out" from the sidebar or top nav.
2. confirm that you are actually logged out-- The top nav should say "Log in" instead of your username, and the CMS admin panel should be inaccessible.
=> task/TUP-404: Logout button for both Dashboard and CMS

apps/tup-cms/Dockerfile, apps/tup-cms/src/apps/dashboard/templates/dashboard/dashboard.debug.html, apps/tup-cms/src/apps/dashboard/templates/dashboard/dashboard.html
Consistently hide and show version of footer by using a more reliable flag in the markup.
<details>
- Set page ID (html_page_id) so markup has `<html id="page-dashboard" ...>`.
- Load CMS image that supports `html_page_id` template variable.
</details>
- [TUP-412](https://jira.tacc.utexas.edu/browse/TUP-412)
- **added** `html_page_id` setting in `dashboard(.debug).html` 
- **changed** cms image
1. Log in to Dashboard.
2. Navigate to another page (e.g. `tickets/`, `profile/`, `projects/`).
3. Refresh.
| homepage | login | dashboard | projects (after refresh) |
| - | - | - | - |
| ![homepage](https://user-images.githubusercontent.com/62723358/217674442-9ce91411-860f-4a8a-b36a-9fd9ba42d338.png) | ![login](https://user-images.githubusercontent.com/62723358/217674441-629caac1-2b35-4d2a-a4e0-f31 …
=> fix(tup-cms): tup-412, giant dashboard footer

libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/projects/users/UserDetail/UserDetail.tsx
Use a dropdown selector for setting user roles.
- [TUP-405](https://jira.tacc.utexas.edu/browse/TUP-405)
- Update the UserRoleSelector to use a dropdown instead of an add/remove link.
1. Set a user as a delegate on a project.
2. Change the user's role back to a "standard" user.
Default view (user is not a PI or is looking at their own role)
Default view for PI looking at standard user: 
Confirmation view when a new role is selected:
=> task/TUP-405: Dropdown UI for delegate selection

libs/tup-components/src/projects/details/ProjectDetails.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantDelete.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationDelete.tsx, libs/tup-hooks/src/projects/index.ts, libs/tup-hooks/src/projects/useGrants.ts, libs/tup-hooks/src/projects/usePublications.ts
Add UI for deleting publications and grants on projects.
- Add hooks for deleting pubs/grants.
- Add components that confirm the user's intent before they delete a pub/grant.
1. Go to a project you have PI/delegate privileges on and delete a publication.
2. Go to a project you have PI/delegate privileges on and delete a grant.
Default view:
After clicking "Delete":
=> task/TUP-406: Add UI for deleting publications and grants on projects

apps/tup-cms/Dockerfile
Fix TUP-412 (and maybe others) by using the latest Core-CMS image.
- fix [TUP-412](https://jira.tacc.utexas.edu/browse/TUP-412) again
1. Test [TUP-412](https://jira.tacc.utexas.edu/browse/TUP-412) again.
| login | homepage | dashboard - projects | dashboard |
| - | - | - | - |
| ![login](https://user-images.githubusercontent.com/62723358/217950118-ce5e1c88-3198-4cfa-9fcb-892302ddc16e.png) | ![homepage](https://user-images.githubusercontent.com/62723358/217950124-af4fb05d-a44d-43b1-b3a5-b82b8b514bef.png) | ![dashboard - projects](https://user-images.githubusercontent.com/62723358/217950127-5a66505e-8c36-44b7-90c4-1796544d0957.png) | ![dashboard](https://user-images.githubusercontent.com/62723358/217950128-8b404322-598f-4d9c-b26a-8ac25cb2573b.png) |
=> fix(tup-cms): get latest core-cms image / tup-412

apps/tup-cms/Dockerfile, package-lock.json, package.json
Table styles updates from Core-Styles.
> **After Merge:**
> Delete https://dev.tup.tacc.utexas.edu/admin/djangocms_snippet/snippet/35/.
- requires https://github.com/TACC/Core-Styles/pull/127
- requires https://github.com/TACC/Core-CMS/pull/603
See https://github.com/TACC/Core-Styles/pull/127.
And:
- single-column tables with paragraphs: [demo](https://dev.tup.tacc.utexas.edu/static/ui/components/detail/table--via-paragraphs-cms.html), [example](https://dev.tup.tacc.utexas.edu/education/educators/publications/), classes: s-paragraph-table or paragraph-table
- default table styles vs. cms table styles: [basic default](https://dev.tup.tacc.utexas.edu/static/ui/components/detail/table--default.html), [basic cms](https://dev.tup.tacc.utexas.edu/static/ui/components/detail/table--cms.html) …
=> chore(core-styles): tup-cms table style updates

libs/tup-components/src/projects/ProjectsTable.tsx
Add filters so we only show active projects/allocations in the Projects section on the Dashboard.
- [TUP-413](https://jira.tacc.utexas.edu/browse/TUP-413)
- Filter allocation list to only use active allocations
- Filter projects list for projects with at least 1 active allocation.
before:
after:
=> bug/TUP-413: Show only active projects/allocations in the Dashboard

libs/tup-components/src/projects/users/UserDetail/UserDetail.tsx
Add text that was in [design](https://xd.adobe.com/view/cc3dc245-2792-4e10-bdc1-50d2a7d32979-996e/screen/30a8fb69-771f-4f00-aa30-98902ca6d2be/specs/), but not in UI.
- [New TUP Testing Session 2 - User Group Feedback](https://confluence.tacc.utexas.edu/display/UP/New+TUP+Testing+Session+2+-+User+Group+Feedback)
https://user-images.githubusercontent.com/62723358/219503007-a0465f55-4a23-4b5a-acd5-7f6c01b31489.mov
=> fix(tup-ui): manage acct, add missing "Confirm Removal" text

libs/tup-components/src/projects/ProjectsListing/ProjectSummary.tsx
We were using "compute requested" instead of the actual compute in the allocation, which was causing projects to show up with >100% resource usage.
- [TUP-418](https://jira.tacc.utexas.edu/browse/TUP-418)
=> task/TUP-418: use correct attributes for calculating percent usage on allocations

libs/tup-components/src/projects/ProjectsListing/ProjectsListingAllocationTable.tsx
Right now all inactive projects have an empty allocations table. We got a comment that we should show inactive allocations for these, since they might be useful for historical purposes.
- [TUP-417](https://jira.tacc.utexas.edu/browse/TUP-417)
=> task/TUP-417: Show inactive allocations for inactive projects

apps/tup-ui/src/pages/Dashboard/Dashboard.module.css, apps/tup-ui/src/pages/Mfa/Mfa.module.css, apps/tup-ui/src/pages/ProjectView/ProjectView.module.css, apps/tup-ui/src/pages/ProjectView/ProjectView.tsx, apps/tup-ui/src/pages/Projects/Projects.module.css, apps/tup-ui/src/pages/Projects/Projects.tsx, libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx, libs/tup-components/src/layout/PageLayout/PageLayout.module.css, libs/tup-components/src/layout/Sidebar/Sidebar.module.css, libs/tup-components/src/projects/ProjectsListing/ProjectsListing.module.css, libs/tup-components/src/projects/ProjectsListing/ProjectsNavbar.tsx, libs/tup-components/src/projects/details/ProjectDetails.module.css, libs/tup-components/src/projects/header/ProjectHeader/ProjectHeader.tsx, libs/tup-components/src/projects/header/ProjectHeader/Projects.module.css, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/projects/users/UserList/UserList.module.css, libs/tup-components/src/tickets/Tickets.module.css, libs/tup-components/src/tickets/Tickets.tsx
To match the mockups, we need a way for a layout's content to be flush with the sidebar and have borders run all the way to the bottom of the page. This isn't compatible with the setup of our `<PageLayout/>` component, which enforces default section padding on the contend div. Unfortunately there's no way to turn the padding off selectively because it's applied **upstream** of the content. The solution is to remove the padding, make the content flush with its surroundings by default, and have the content set its own padding.
| before | after | 
| -- | -- | 
| <img width="1580" alt="image" src="https://user-images.githubusercontent.com/12601812/219412463-5156b05f-93d5-496f-ac1f-1c4f06383d42.png"> | <img width="1578" alt="image" src="https://user-images.githubusercontent.com/12601812/2194120 …
=> Support flush layouts in the Projects area

apps/tup-cms/src/apps/portal/templates/portal/portal.debug.html, apps/tup-cms/src/apps/portal/templates/portal/portal.html
Change template ID for Portal pages.
- https://github.com/TACC/tup-ui/pull/157
1. Confirm Portal and Login pages have `<html id="page-portal">`.
1. Confirm CMS pages do __not__ have `<html id="page-portal">`.
| portal, projects | portal, dashboard | portal, login | cms, home |
| - | - | - | - |
| ![projects](https://user-images.githubusercontent.com/62723358/220789476-e66c766c-6471-413f-840b-661cc9d5aa10.png) | ![dashboard](https://user-images.githubusercontent.com/62723358/220789477-c32ebbc2-f6f6-46db-9338-77b7b0a82808.png) | ![login](https://user-images.githubusercontent.com/62723358/220789478-370a1477-9fb5-4e0d-9652-72cd74c3d111.png) | ![cms](https://user-images.githubusercontent.com/62723358/220789479-0dd42e14-847c-4dc4-951b-f9d6e66edbdb.png) |
http://dev.tup.tacc.utexas.edu/ CSS is …
=> Use /portal and not /dashboard in routes… and CMS template ID

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/settings_custom.py
Add and use new setting `SEARCH_QUERY_PARAM_NAME` so CMS search uses parameter that Google expects.
- [TUP-437](https://jira.tacc.utexas.edu/browse/TUP-437)
- requires https://github.com/TACC/Core-CMS/pull/604
- added `SEARCH_QUERY_PARAM_NAME` setting with value "q"
- changed CMS Docker image to one with [TACC/Core-CMS#604](https://github.com/TACC/Core-CMS/pull/604)
1. Ensure a Search page with Search Snippet exists, like:
- dev.tup page: https://dev.tup.tacc.utexas.edu/search/
- dev.tup snippet: https://dev.tup.tacc.utexas.edu/admin/djangocms_snippet/snippet/89/change/
2. Open any CMS page.
3. Verify search `<input>`'s `name` attribute equals `q` (not `query_search`).
4. Search for "test" using search box.
5. Verify search page returns results (because URL has `?q=test`).
| search box | …
=> feat(tup-cms): tup-437, search query param name

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/settings_custom.py
Use image off of `dev/tup-cms`, not `main`; i.e. fix https://github.com/TACC/tup-ui/pull/159#discussion_r1116342250.
=> fix(tup-cms): up-to-date cms search query param name image

apps/tup-cms/src/taccsite_cms/templates/assets_custom_delayed.html
Warn user about trying to overriding `assets_custom_delayed.html` the way other templates can be overridden.
- resolves [concern](https://github.com/TACC/tup-ui/pull/148/files/98d4723#r1107841760) in #148
- add `assets_custom_delayed.html` to `tup-cms` templates
N/A
=> add support for React components in CMS content

libs/tup-components/src/projects/users/UserList/ManageTeam.tsx
Clarify that Users can only be added by exact username
- [TUP-435](https://jira.tacc.utexas.edu/browse/TUP-435)
We should eventually implement the ability to search by username/name
=> Clarify that 'Add User' should use exact username

libs/tup-components/src/tickets/TicketsTable.test.tsx, libs/tup-components/src/tickets/TicketsTable.tsx, libs/tup-testing/src/mocks/handlers.ts
Add an attachment indicator to show which tickets have attachments.
- [TUP-430](https://jira.tacc.utexas.edu/browse/TUP-430)
1. Make sure that you have at least 1 ticket with an attachment
2. Check that that ticket has the "link" icon next to it in the tickets table in the Tickets and Dashboard views.
=> task/TUP-430: Add indicator for tickets with attachments

apps/tup-cms/src/apps/portal_nav/templates/portal_nav/nav_portal.raw.html, apps/tup-ui/src/pages/Dashboard/Dashboard.tsx, libs/tup-components/src/layout/Sidebar/Sidebar.tsx
- [TUP-434](https://jira.tacc.utexas.edu/browse/TUP-434)
1. Remove Manage Account from Dashboard top-right.
2. Remove Log Out from Left-Nav-Bar
3. Add Manage Account to Left-Nav-Bar
4. Add Manage Account to User Dropdown (top-right)
1. Dashboard -- confirm Manage Account is no longer there. 
2. Left-Nav -- confirm Log Out is no longer there.
3. Left-Nav -- confirm Manage Account is there with the correct 'user' icon and link to the correct page (portal/account)
4. Dropdown -- confirm Manage Account is there with the correct 'user' icon and link to the correct page (portal/account)
=> make changes to manage account through out site

apps/tup-ui/src/App.tsx, apps/tup-ui/src/pages/Dashboard/Dashboard.tsx, apps/tup-ui/src/pages/Tickets/TicketDetail.tsx, libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx, libs/tup-components/src/accounts/ManageAccountMfa.tsx, libs/tup-components/src/projects/details/ProjectEdit/ProjectEditModal.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantCreateModal.tsx, libs/tup-components/src/projects/details/grants/ProjectGrantEditModal.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationCreateModal.tsx, libs/tup-components/src/projects/details/publications/ProjectPublicationEditModal.tsx, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/projects/users/UserDetail/UserDetail.tsx, libs/tup-components/src/projects/users/UserList/UserList.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateModal.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketHistory.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.global.css, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.test.tsx, libs/tup-components/src/tickets/TicketDetailModal/TicketModal.tsx, libs/tup-components/src/tickets/Tickets.tsx, libs/tup-components/src/tickets/TicketsDashboard.tsx, libs/tup-components/src/tickets/TicketsTable.tsx
Modals:
- Modals should be vertically centered. (This is common practice.)
- When clicking ticket, modal should open, but not go to tickets section.
- Modal height should open at a max height (~70vh), not change in height as content height changes.
Projects:
- Add explanatory text to user allocations panel.
- Highlight the special users (PI, Co-PI, Delegate) in the user list, and style their role distinct from their name
Tickets:
- Tickets Modal should open with most recent ticket unfurled by default.
- Change order of ticket reply header content, i.e. align timestamp to the right, e.g.:
name      content...     timestamp
Manage Account: 
- Buttons should not be clickable to the right of the button
"PI"/"Delegate" styling (non-bolded like in the mockups).
Project role explanations:
Ticket …
=> Fixes for CMD feedback items

apps/tup-cms/src/apps/portal/templates/portal/portal.debug.html, apps/tup-cms/src/apps/portal/templates/portal/portal.html, apps/tup-cms/src/apps/user_news/templates/user_news/list.html, apps/tup-cms/src/apps/user_news/templates/user_news/read.html
Some apps fail to read from CMS page title (they show a URL, the CMS fallback).
- Set page title manually for pages that do **not** read from CMS:
- portal
- portal (debug)
- Use page title from CMS on pages that **can** read from CMS:
- list
- Set page title manually for pages for which we can not re-create each child on CMS:
- read
- portal
- portal (debug)
Verify the following pages have titles:
- https://dev.tup.tacc.utexas.edu/portal/login
- https://dev.tup.tacc.utexas.edu/portal/
- https://dev.tup.tacc.utexas.edu/portal/tickets
- https://dev.tup.tacc.utexas.edu/news/user-updates
Changed to "User Portal" after this screenshot was taken.
Changed to "User Portal" after this screenshot was taken.
Changed to "User Portal" after …
=> fix(tup-cms): use/set page title on app pages

apps/tup-cms/Dockerfile, package-lock.json, package.json
New CMS (and Docs) message styles. They will be ported to Portal later.
- https://github.com/TACC/Core-Styles/pull/131
- new CMS image
- install core-styles at [merge commit of #131](https://github.com/TACC/Core-Styles/pull/131)
Compare these webpages to styles from screenshots in https://github.com/TACC/Core-Styles/pull/131:
- https://dev.tup.tacc.utexas.edu/static/ui/components/detail/admonition.html
- https://dev.tup.tacc.utexas.edu/static/ui/components/detail/c-message--type.html
=> feat(tup-cms): new message styles

apps/tup-cms/src/taccsite_cms/settings_custom.py
Allow folder-level permissions in Django CMS.
- learned during https://github.com/TACC/tup-ui/pull/171
- add one setting, set to True
> @wesleyboar tested this on dev.tup via #171, on 2023-02-27 for groups "EPIC Newsletter Manager" and 2023-02-28 for "Media Editor (Basic)". The screenshots below record the latter test.
1. Create/Find group with relevant perms.
2. Add/Find user in that group.
3. Set/Verify folder perms for that group.
4. Login as that user.
5. Verify "Filer" (file management app in CMS) only shows the folder user can read.
6. Verify user can read folder.
=> feat(tup-cms): allow folder-level permissions

libs/tup-components/src/projects/details/ProjectDetails.module.css, libs/tup-components/src/projects/details/ProjectDetails.test.tsx, libs/tup-components/src/projects/details/ProjectDetails.tsx
Changes to Project Page - abstract and grants go to TXRAS
- [TUP-442](https://jira.tacc.utexas.edu/browse/TUP-442)
1. Move Publications to be below Allocations
2. Remove Abstract section
3. Remove Grants section
4. Make combined Abstract/Grants section that links to TXRAS (https://submit-tacc.xras.org/requests)
1. Dashboard --> Projects & Allocations (left-nav)
2. Select a project
3. Make sure the three main sections are Allocations, Publications, Abstract/Grants
4. Clicking Edit Project next to Abstract/Grants goes to TXRAS.
BEFORE:
AFTER:
=> combine abstract/grants section, links to TXRAS

apps/tup-ui/src/main.global.css, libs/core-components/src/lib/InfiniteScrollTable/InfiniteScrollTable.css, libs/tup-components/src/projects/ProjectsListing/ProjectsListing.module.css, libs/tup-components/src/projects/ProjectsTable.tsx, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css, libs/tup-components/src/system_monitor/SystemMonitor.module.css, libs/tup-components/src/tickets/TicketsTable.tsx
Avoid repeating `width: 100%` on every table.
None.
- **removed** table width 100% instances
- **added** one table width 100% definition
1. Open Dashboard, Projects, and Tickets.
2. Verify all tables are still 100% width.
| many table width 100% (before) | no table width 100% (during) | one table width 100% (after) |
| - | - | - |
| ![many table widths 1](https://user-images.githubusercontent.com/62723358/225147313-9475965d-b5f1-4150-97c4-6abd306da491.png) | ![remove table widths 1](https://user-images.githubusercontent.com/62723358/225147317-27ae02e8-26ab-4119-b124-844d780db8f3.png) | ![add global table width 1](https://user-images.githubusercontent.com/62723358/225147319-0c599148-b412-4e60-90bc-06191cf2eb7d.png) |
| ![many table widths …
=> chore(tup-ui): no repetition of table width 100%

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/templates/404.html
1. Add manual **404** page (that overwrites a simpler one from Core-CMS).
2. Get `djangocms_picture` template bug fixes form Core-CMS.
- **[feat: minimal 404 error page](https://github.com/TACC/Core-CMS/commit/ea034fc) (https://github.com/TACC/Core-CMS/commit/ea034fc)**
- https://github.com/TACC/Core-CMS/pull/610
- and [fix(djangocms_picture): missing "not" in if clause](https://github.com/TACC/Core-CMS/commit/0340445) (https://github.com/TACC/Core-CMS/commit/0340445)
- **changed** Core-CMS image
1. On dev.tup.tacc.utexas.edu, visit a page that does not exist e.g. https://dev.tup.tacc.utexas.edu/sadf/.
2. **Verify a 404 status code.**
3. Verify 404 page has standard header and footer.
Used in #182.
=> fix(tup-cms): core-cms templates: picture, 404

libs/core-components/src/lib/Pill/Pill.module.css
Reduce pill size on CMS. (But not on Portal, yet.)
- reduce pill size (only has visible effect on cms)
0. `nx build tup-cms`, `nx serve tup-cms`, `nx serve tup-ui`
1. Verify font-size of pill is smaller on CMS. (Smaller font than table.)
2. Verify font-size of pill is unchanged on Portal. (Same size font as table.)
| cms | portal |
| - | - |
| ![cms](https://user-images.githubusercontent.com/62723358/225955549-a8468365-010f-4f0c-ab8c-ef92a6f73575.png) | ![portal](https://user-images.githubusercontent.com/62723358/225955543-84da5fe8-203f-4fb5-a0cd-559b325793cc.png) |
Font size or pill is not small enough on portal, relative to table size. But table size on portal (matches core-styles.base) is smaller than CMS (overrides …
=> fix(tup-cms): pill size too large (on cms)

apps/tup-cms/Dockerfile, package-lock.json, package.json
**https://github.com/TACC/Core-Styles**
- [**v2.6.1**: core-styles.wysiwyg.css](https://github.com/TACC/Core-Styles/releases/tag/v2.6.1) [Latest](https://github.com/TACC/Core-Styles/releases/latest)
- [**v2.6.0**: c-tag & --global-font-size--xxx-large & c-island](https://github.com/TACC/Core-Styles/releases/tag/v2.6.0)
Expect no effect. Relevance is that it adds more patterns to `core-styles.base.css` that CMS will use.
https://user-images.githubusercontent.com/62723358/226769267-ef21cc80-7d03-4f1a-bb01-7c29a40362a7.mov
=> chore(core-styles): v2.6.1

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/settings_custom.py
Turn off search bar (until Google re-indexes).
- requires https://github.com/TACC/Core-CMS/pull/614
- **added** setting to disable search bar
1. Verify search bar is not present.
2. Verify flexible horizontal space in header between CMS Nav and Portal Nav.
=> test(tup-cms): turn off search bar

apps/tup-cms/src/taccsite_custom/tup-cms/static/tup-cms/js/modules/breadcrumbs.js
Fix innocuous JavaScript error (on Full Width template pages) while manipulating breadcrumbs.
- **changed** condition to check whether link exists
1. Open homepage (set to Full Width template).
2. Have console open.
3. Verify no error in `breadcrumbs.js`.
4. Open another page (set to Standard template).
5. Have console open.
6.  Verify no error in `breadcrumbs.js`.
Skipped.
On a full width template, no breadcrumbs exist, thus no `link` exists from which to `removeAttribute`.
=> fix(tup-cms): full width template, avoid js error

apps/tup-cms/src/taccsite_custom/tup-cms/static/tup-cms/css/for-tup-cms/components/c-news.css
Hide byline on a "User Updates" article.
- fixes #191
- **added** code to hide byline in "not blog app" context
1. Verify that byline is not shown on [a User Updates article that has not been updated with more news](https://dev.tup.tacc.utexas.edu/news/user-updates/107446/).
| list | read |
| - | - |
| ![list](https://user-images.githubusercontent.com/62723358/231011237-bc717f30-56f3-4ae9-87e7-4399cf98245e.png) | ![read](https://user-images.githubusercontent.com/62723358/231011234-cd06eb7e-12f1-4085-b578-ec715869ecd1.png) |
=> fix(tup-cms): hide byline on user updates

apps/tup-cms/src/taccsite_custom/tup-cms/static/tup-cms/css/for-tup-cms/components/banner.css
Let main banner image fill full width available.
None
- **added** back a style I should not have removed
1. Verify top banner image on [home page](https://dev.tup.tacc.utexas.edu/) takes up full width of page.
| - | - |
| ![before](https://user-images.githubusercontent.com/62723358/231258006-aad0ac80-db9e-44e4-ab8c-ade654d967e7.png) | ![after](https://user-images.githubusercontent.com/62723358/231258451-6aced0b6-9823-4e9f-9fdb-3664b0cb78cb.png) |
=> fix(tup-cms): let banner image "size-to-fit"

libs/tup-components/src/projects/ProjectsListing/ProjectsListing.tsx, libs/tup-components/src/projects/ProjectsTable.tsx
It was possible to get a totally blank projects listing if you had projects but they were all inactive. This PR makes it so that we always show at least the warning.
=> fix: Show text for empty projects if user has inactive projects

libs/tup-components/src/auth/LoginComponent/LoginComponent.spec.tsx, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Add password reset link to login page
- [TUP-452](https://jira.tacc.utexas.edu/browse/TUP-452)
1. visit http://localhost:8000/portal/login?from=/portal/ and check that the password reset link shows up.
=> task/TUP-452: Add password reset link to login page

apps/tup-cms-react/imports.debug.html, apps/tup-cms-react/imports.html
The tup-cms-react templates were using a hard-coded tup-services URL that was overriding the configuration. This prevents them from doing so if the setting has already been loaded (e.g. inside of the portal).
=> Tweak: Stop tup-cms from overriding TUP_SERVICES_URL config

apps/tup-cms/src/apps/portal/apps.py, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.test.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx, libs/tup-components/src/tickets/index.ts
Address concerns from User Services about routing/categorization of tickets.
- [TUP-218](https://jira.tacc.utexas.edu/browse/TUP-218)
- Add Category and Resource as required fields in the Create Ticket form, and append them to the ticket body.
- Route tickets to different RT queues based on their category:
Data Analy > data
Login > accounting
Running Jobs > hpc
Security > nso
Other > hpc
1. From the user portal, submit a ticket with some Category selected.
2. Confirm that the ticket appears in Consult under the correct queue as mapped above.
=> task/TUP-218: Add resource/category to ticket body and choose queue based on category

apps/tup-ui/src/pages/Login/Login.tsx
Enable link on Login page that was disabled.
- launch issues
- **changed** a disabled button to a real link
1. Be logged out.
2. Visit login page.
3. Click "Policies" link.
4. Verify "User Policies" page loads (`/use-tacc/user-policies/`)*
<sub>* live site: https://tacc.utexas.edu/use-tacc/user-policies/</sub>
https://user-images.githubusercontent.com/62723358/233702516-124163d3-5d91-4516-97af-52dfae493a12.mov
=> fix(tup-ui): enable policies link on login page

libs/tup-components/src/accounts/ManageAccountMfa.tsx, libs/tup-hooks/src/mfa/index.ts, libs/tup-hooks/src/mfa/useMfa.tsx
Add UI for unpairing MFA via email.
- [TUP-456](https://jira.tacc.utexas.edu/browse/TUP-456)
(with https://github.com/TACC/tup-services/pull/31 checked out/running and `TUP_SERVICES_URL = "http://localhost:8001"` in settings)
1. Navigate to the "Manage Account" page and click "Unpair" next to your MFA pairing.
2. Follow the instructions in the modal to send an email (this may only work in local dev for TACC emails).
=> UI for unpairing MFA via email

libs/tup-components/src/accounts/ManageAccountMfa.tsx, libs/tup-components/src/mfa/Mfa.module.css, libs/tup-components/src/mfa/MfaQRPanel.tsx, libs/tup-components/src/mfa/MfaSmsPanel.tsx
Some pieces of the MFA pairing flow had poorly defined error handling. This PR makes it more explicit when the backend fails to create or retrieve a pairing, and directs the user to submit a ticket.
- [TUP-465](https://jira.tacc.utexas.edu/browse/TUP-465)
=> Improve error handling for MFA

libs/tup-components/src/tickets/TicketDetailModal/TicketModal.tsx
Prevent ticket detail modal from overflowing the viewport by removing the `fit-content` css directive.
- [TUP-467](https://jira.tacc.utexas.edu/browse/TUP-467)
1. Open a ticket detail with a large reply chain or a large reply body (large enough to overflow the viewport
2. Make sure that you can scroll through the entire ticket reply chain.
=> task/TUP-467: Prevent ticket detail modal from overflowing the viewport

libs/tup-components/src/projects/ProjectLayout.test.tsx, libs/tup-components/src/projects/ProjectsListing/ProjectSummary.tsx, libs/tup-components/src/projects/ProjectsTable.test.tsx, libs/tup-components/src/projects/ProjectsTable.tsx, libs/tup-components/src/projects/details/ProjectDetails.tsx, libs/tup-components/src/projects/header/ProjectHeader/ProjectHeader.tsx, libs/tup-hooks/src/projects/index.ts
Handle cases where a project has no title/description in TAS. This can be the case for some very old projects.
- [TUP-465](https://jira.tacc.utexas.edu/browse/TUP-465)
- Replace null title/descriptions with `Untitled Project`/`(No description provided)`.
- Add the charge code to the project listing in the dashboard.
=> bug/TUP-465: Handle null project title/description

apps/tup-cms/Dockerfile
Document which Core-CMS image is currently being used.
<sup>Because it is a CMS commit within a branch (`django/2to3--tup-cms--tup-477`) off a branch (`django/2to3--tup-cms`) off a branch (`dev/tup-cms`) off of `main`.</sup>
- documents a change introduced in #225
=> docs(tup-cms): note core-cms image/commit used

libs/tup-components/src/tickets/TicketDetailModal/TicketReplyForm.tsx, libs/tup-hooks/src/tickets/useTickets.ts
Add a `status` form field so that users can set the status of their ticket when replying.
- [TUP-468](https://jira.tacc.utexas.edu/browse/TUP-468)
- Update the ticket reply form with a dropdown for ticket status.
- Update the `useTicketReply` hook to invalidate the tickets cache on success (to pick up on the new status).
1. Reply to a ticket you own and set its status. Confirm that the selected status is reflected in the UI/history.
=> task/TUP-468: Allow users to set ticket status from the reply form

libs/tup-components/src/tickets/TicketDetailModal/TicketReplyForm.tsx
Default to having RT set the status for tickets if the user doesn't make a selection. This restores the intended behavior of having replies to resolved tickets set the ticket status back to "open".
- [TUP-468](https://jira.tacc.utexas.edu/browse/TUP-468)
=> task/TUP-468 (fix): Default to NOT passing a custom status when replying to tickets

apps/tup-cms/src/apps/portal/views.py, apps/tup-cms/src/apps/portal_nav/templates/portal_nav/nav_portal.raw.html
Some users need "staff" status to edit CMS content but should NOT be allowed to impersonate users. Existing impersonators will be upgraded to "superuser" status and the impersonation endpoint will be changed to require that status. 
- [TUP-511](https://jira.tacc.utexas.edu/browse/TUP-511)
=> task/TUP-511: Require superuser status to impersonate others

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
Maverick2 is being decommissioned, so this PR removes it from the "resources" dropdown when creating a ticket.
- [TUP-512](https://jira.tacc.utexas.edu/browse/TUP-512)
=> task/TUP-512: remove Maverick2 from ticket creation form

libs/tup-components/src/mfa/MfaSelection.tsx, libs/tup-components/src/mfa/MfaValidationPanel.tsx
Frontend component of TUP-516. Prevents users from being automatically redirected to the SMS pairing screen if they have previously generated an SMS token and backed out before verifying it.
- [TUP-516](https://jira.tacc.utexas.edu/browse/TUP-516)
1. Unpair your current MFA token.
2. Click "pair device" and enter your phone number for SMS pairing, but DO NOT validate with the code.
3. Back out of MFA pairing and attempt to pair using a token app.
=> task/TUP-516: Prevent users from getting locked into SMS pairing

apps/tup-cms/src/apps/portal/views.py, apps/tup-cms/src/apps/portal_nav/templates/portal_nav/nav_portal.raw.html, apps/tup-cms/src/apps/portal_nav/views.py
Use a specific Impersonator group to manage impersonation permissions.
- [TUP-511](https://jira.tacc.utexas.edu/browse/TUP-511)
1. Add yourself to the Impersonator group (create it if it doesn't exist)
2. Check that you can impersonate users via the nav dropdown.
3. Remove yourself from Impersonator and make sure your permissions are actually revoked.
=> task/TUP-511: Use a specific Impersonator group to manage impersonation permissions.

libs/tup-components/src/system_monitor/details/SystemDetails.module.css, libs/tup-components/src/system_monitor/details/SystemDetails.tsx
Make new systems section accessible on small windows.
- tweaks #234
- **removed** old `SystemDetails` CSS*
- **added** new `SystemDetails` CSS*†
- **changed** `SectionDetails` markup to:
- wrap only the table that needs to scroll
- make able to scroll the table that should scroll
- use markup similar to Dashboard†
<sup>* The `SystemNavBar` CSS is untouched. It should be moved out to its own CSS file; I'll comment about this in #234.</sup>
<sup>† The `Dashboard` layout is most similar to the new design. I referenced its markup and CSS.</sup>
1. Open http://localhost:8000/portal/system_status 
2. View layout on wide screen:
1. All panels with content should stack vertically.
2. _The panel without content should be on the fight side of those with content._
3. All panels should have the same …
=> feat: support smaller windows

libs/tup-components/src/system_monitor/details/SystemDetails.module.css, libs/tup-components/src/system_monitor/details/SystemDetails.tsx
Simplify system section layout code.
- tweaks #234
<sup>(via #257)</sup>
- follow up to #256
- **changed** `SystemDetails` grid layout to not use a nested grid
1. Open http://localhost:8000/portal/system_status 
2. View layout on wide screen:
1. All panels with content should stack vertically.
2. _The panel without content must be on the fight side of those with content._
3. All panels must have the same space between them.
4. Extra space must not exist.*
3. View layout on narrow screen:
1. All panels (with and without content) should stack vertically.
2. _The panel without content must be on the bottom._
3. All panels must have the same space between them.
4. Extra space must not exist.*
5. Panel with more rows than can be shown must have scroll bar.
| | short | tall |
| - | - | - |
| …
=> Task/TUP-457/TUP-514 Add System Queue Details - content layout - phase 2

libs/tup-components/src/mfa/MfaSelection.tsx
Clear "Unchanged files with check annotations" from Github.
<details><summary>Screenshot</summary>
</details>
- fix Github complaints on https://github.com/TACC/tup-ui/pull/248/files
- **removed** unused imports
Skipped. I am relying on automation and peer review to verify the "noop"-ness of this change.
=> chore: remove unused imports

apps/tup-ui/src/main.global.css, apps/tup-ui/src/main.global.for-core-styles.css, libs/tup-components/src/news/UserNews.module.css, libs/tup-components/src/news/UserNews.tsx
Make "User Updates" more closely match CMS markup and styles.
<sup>Ideally, these lists use the same classes and even markup. Not yet. I'll do that in another PR.</sup>
- [**TUP-519**](https://jira.tacc.utexas.edu/browse/TUP-519)
- [TUP-532](https://jira.tacc.utexas.edu/browse/TUP-532)
- does **not** fix [TUP-490](https://jira.tacc.utexas.edu/browse/TUP-490) **nor** [TUP-422](https://jira.tacc.utexas.edu/browse/TUP-422)
- **added** global `<h3>` styles
<sup>(probably destined for core-styles)</sup>
- **added** global `[data-prefix]` styles
<sup>(destined for core-styles)</sup>
- **changed** `UserNews.module.css`
<sup>(to mimic `.c-feed-list` used by `user_news` app)</sup>
<sup>(placeholder fixes until portal uses `.c-feed-list`)</sup>
- **changed** `UserNews.tsx`
<sup>(to mimic markup …
=> fix(tup-components, tup-ui): tup-519 UserNews component UI

apps/tup-cms/src/apps/user_news/defaults.py, apps/tup-cms/src/apps/user_news/templates/user_news/includes/item_data.html, apps/tup-cms/src/apps/user_news/templates/user_news/includes/list_item.html, apps/tup-cms/src/apps/user_news/templates/user_news/includes/list_item_for_plugin.html, apps/tup-cms/src/apps/user_news/utils.py, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-feed-list.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news--list.css
Fix "User Updates" plugin UI bugs (also in #248 for portal).
- [TUP-532](https://jira.tacc.utexas.edu/browse/TUP-532)
- found during #248
- **changed** "Update" pill to be in date (not title)
- **changed** date to be prefixed by the text "Published: " (not "Posted: ")
- **removed** _inconsistent_ whitespace from title
- **added** _consistent_ whitespace from title
1. Verify "Update" pill markup is moved from title to date.
2. Verify "Update" pill has no visual change compared to production.
3. Verify date is prefixed by the text "Published: " (not "Posted: ").
4. Verify space between "Update" pill and article title comes from CSS not whitespace character in title hyperlink.
| | html space<br /><sup>(none)</sup> | css space<br /><sup>(some)</sup> |
| - | - | - |
| …
=> fix(tup-cms): tup-532 user_news plugin UI

apps/tup-cms/src/apps/portal/apps.py, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx, libs/tup-components/src/tickets/index.ts
Previously there was a Login/Authentication Issues option pointing  to the Accounting queue as well as a Login Issues option going to the Accounts queue. These are combined now and the Accounting queue has been deprecated.
=> Task/tup 533:  Remove duplicate Login option from ticket form

libs/tup-components/src/system-status/details/SystemNavBar.tsx
Remove superfluous divs and unused classes.
Inspired by https://github.com/TACC/tup-ui/pull/266#discussion_r1262811191.
- polishes #266
1. Verify loading, error, and success state for SystemNavBar are unchanged.*
<sup>* To test this, I changed corresponding `error` and `isLoading` to `true`.</sup>
| success | loading | error |
| - | - | - |
| <img width="775" alt="success" src="https://github.com/TACC/tup-ui/assets/62723358/b0bbff4f-535f-4526-8df7-f0efb0d3e627"> | <img width="775" alt="loading" src="https://github.com/TACC/tup-ui/assets/62723358/8dcea6c9-d6fe-4047-9584-beea9756f210"> | <img width="775" alt="error" src="https://github.com/TACC/tup-ui/assets/62723358/e5cb8139-b030-472e-96dd-d45824abd8d6"> |
=> Task/tup 514 merging content layout system status - remove UI cruft

libs/core-components/src/lib/Button/Button.test.jsx, libs/core-components/src/lib/Button/Button.tsx, libs/tup-components/src/projects/users/UserDetail/UserDetail.module.css
Remove unnecessary `<span>` from `<Button>`.
<sup>This can fix edge case alignment issues, like in #270 or the style this PR outdates and removes.</sup>
- required by #270
1. Verify button bottom "padding" is a pixel or so less.
2. Verify `<UserDetail>` `link-button` is unaffected by change.
3. Check any UI you know may be adversely affected.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/e32d90b8-2398-4574-b7eb-79367c679c96) | ![after](https://github.com/TACC/tup-ui/assets/62723358/04028945-8498-4d1a-96a7-b8ce08610c9b) |
https://github.com/TACC/tup-ui/assets/62723358/48c51559-52d5-4586-8b39-e6db88b1fdf8
https://github.com/TACC/tup-ui/assets/62723358/687d7d3f-4ed9-4a36-9049-bca891ea8e3e
The `<span>` inside <Button> is unnecessary and can cause …
=> fix: button text alignment, excess button markup & space

libs/tup-components/src/mfa/MfaValidationPanel.tsx
1. Remove "to continue the pairing" from MFA QR code pairing step 2.
- [TUP-542](https://jira.tacc.utexas.edu/browse/TUP-542)
| - | - |
| ![1 before](https://github.com/TACC/tup-ui/assets/62723358/5c035339-c1be-4ede-a740-528330949770) | ![1](https://github.com/TACC/tup-ui/assets/62723358/21af4165-29d2-4c30-90d3-18906844a70d) |
=> fix: tup-542 (1) remove "to continue the pairing"

libs/tup-components/src/accounts/ManageAccountMfa.tsx
Do not nest a `<p>` within a `<p>`.
- removed superfluous `<p>`
1. Have MFA pairing.
2. Open modal to unpair MFA.
Rendered Markup:
Logged Error:
Source Markup:
No nested `<p>` tag, yet same UI:
=> fix: invalid markup in mfa

libs/tup-components/src/accounts/ManageAccountMfa.tsx
3. From unpair modal, remove "Enter your current MFA token… paragraph.
- [TUP-542](https://jira.tacc.utexas.edu/browse/TUP-542)
| - | - |
| ![3 before](https://github.com/TACC/tup-ui/assets/62723358/aa3c8137-c22c-470f-a3e0-271be0b91000) | ![3](https://github.com/TACC/tup-ui/assets/62723358/405e6762-f1ed-4a5d-89fb-ba960204c8dc) |
=> fix: tup-542 (3) unpair modal, drop excess text

libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccountMfa.tsx
4. Change "Unpair" link to the right of token status to be a button underneath token status.
- [TUP-542](https://jira.tacc.utexas.edu/browse/TUP-542)
| - | - |
| ![4 before](https://github.com/TACC/tup-ui/assets/62723358/fbf9c878-ecc0-4ba0-a5cc-35f5f1a99abe) | ![4](https://github.com/TACC/tup-ui/assets/62723358/16004bea-ac80-4f48-9b3a-46b7b23818ac) |
=> fix: tup-542 (4) unpair link to right → button underneath

apps/tup-cms-react/src/Sysmon/Sysmon.tsx, libs/tup-components/src/system-status/SystemMonitor.tsx, libs/tup-components/src/system-status/SystemMonitorCells.tsx, libs/tup-components/src/system-status/index.ts
Make the react-router dependency optional for the sysmon table, fixing its rendering inside of CMS snippets.
- [TUP-544](https://jira.tacc.utexas.edu/browse/TUP-544)
- add an optional `useLinks` prop (defaulting to true) that toggles whether the table displays system names as links (for the portal) or plain text (for the CMS component).
- Render the `SystemMonitorTable` component with `useLinks={false}` and check that the component renders without react-router links.
=> bug/TUP-544: Remove dependency on react-router from CMS sysmon

libs/tup-components/src/mfa/MfaSmsPanel.tsx, libs/tup-components/src/mfa/MfaValidationPanel.tsx
5. Change SMS pairing step 1 message "Didn't receive […] [Get help.](https://example.com/)" to only show after submitting token to send.
- [TUP-542](https://jira.tacc.utexas.edu/browse/TUP-542)
https://github.com/TACC/tup-ui/assets/62723358/1e4722d7-d98e-4060-a31b-4f66e2c1c1ff
https://github.com/TACC/tup-ui/assets/62723358/60c60214-6f9d-443b-a7eb-f84b1273affb
=> fix: tup-542 (5) show sms pair help msg only after submit

apps/tup-cms/src/apps/user_news/utils.py
Fix a type error that was preventing display of User News stories.
- [TUP-563](https://jira.tacc.utexas.edu/browse/TUP-563)
=> Bug/TUP-563: fix 500 error in user news

apps/tup-cms/src/taccsite_cms/settings_custom.py
New CMS image to mimic https://github.com/TACC/Core-CMS/pull/695 hotfix.
<details><summary>Why not use new CMS image?</summary>
Because the attempt in https://github.com/TACC/tup-ui/pull/301 broke the UI demo.
</details>
- mimics https://github.com/TACC/Core-CMS/pull/695
- alternative to https://github.com/TACC/tup-ui/pull/301
1. In Chrome/ium DevTools > Application > Cookies
2. Confirm "Secure" column for "sessionid" cookie is **checked**.
| Dev Before | Dev After |
| - | - |
| ![tup dev hotfix before](https://github.com/TACC/tup-ui/assets/62723358/1f4f6e84-ebf9-4d61-a3af-b94b8795a87a) | ![tup dev hotfix after](https://github.com/TACC/tup-ui/assets/62723358/cf3bc405-27bd-43e3-bc68-495090ea59c9) |
| Localhost After |
| - |
| ![tup hotfix …
=> hotfix: set SESSION_COOKIE_SECURE = True

apps/tup-cms/src/apps/portal/views.py, libs/tup-hooks/src/auth/useAuth.ts
Set the `secure` attribute on x-tup-token to reduce the risk of hijacking.
- [TUP-564](https://jira.tacc.utexas.edu/browse/TUP-564)
=> Task/TUP-564: Set the `secure` attribute on x-tup-token

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/components/django.cms.blog.app.page.css
Do **not** let blog images on narrow screen exceed width of page.
> **Important**
> This change is applied to live site via [snippet #136](https://www.tacc.utexas.edu/admin/djangocms_snippet/snippet/136/change/). Delete that snippet after this code is deployed.
- fixes bug caused by https://github.com/TACC/Core-CMS#588
- **changed** one CSS value in a stylesheet
<sub>This stylesheet will be used in [TUP-463](https://jira.tacc.utexas.edu/browse/TUP-463) to overwrite Core-CMS styles.</sub>
1. Open https://www.tacc.utexas.edu/news/latest-news/2023/09/13/ecep-connect-virtual-summit/.
2. Confirm article image does not overflow page / cause scrollbar at any screen width, especially 767px or less.
3. For good measure, if news editor is not working ons tory, test when image has a caption.
<sub>To …
=> fix: narrow screen, blog image must have max-width

apps/tup-cms/Dockerfile
Update to Core CMS v3.12 Beta.
- requires https://github.com/TACC/Core-CMS/pull/706
- **changed** core-cms image tag
Most changes do not need testing, because these are all micro-releases with:
- minor changes
- non–user-facing changes
- changes that were in the TUP launch branch
I verified UI demo loads and news page headings are `<h1>`.
- https://github.com/TACC/Core-CMS/pull/706
Verify demo is accessible e.g. https://dev.tup.tacc.utexas.edu/static/ui/.
| v3.12.0-beta.3 candidate | v3.12.0-beta.3  official |
| - | - |
| ![dev tup candidate test](https://github.com/TACC/tup-ui/assets/62723358/c10de83f-79e4-471f-a94a-6c5f7c5f14e4) | ![dev tup official deploy](https://github.com/TACC/tup-ui/assets/62723358/2145a001-73bd-486f-9898-31c5ece1de25) |
- https://github.com/TACC/Core-CMS/pull/674 …
=> chore: upgrade cms to v3.12.0-beta

libs/tup-components/src/tickets/TicketDetailModal/TicketModal.tsx, libs/tup-components/src/tickets/TicketsTable.tsx
Fixes a small annoyance where closing the ticket detail modal then hitting the browser's "back" button would reopen the modal.
- [TUP-570](https://jira.tacc.utexas.edu/browse/TUP-570)
Adds logic to the ticket detail modal to detect whether the user got there from the portal (by clicking a button in the ticket listing) or from outside the portal (by copying a link/opening in a new tab). If we know the user got there from our own link, we can safely navigate back with `navigate(-1)`, otherwise we have to use the `basePath` to navigate.
1. Open and close the detail modal for multiple tickets, then hit the "back" button on your browser. You should immediately go back to wherever you were before navigating to the dashboard/ticket page, instead of having to hit the button multiple times.
2. …
=> bug/TUP-570: Fix router history behavior in the Ticket Detail modal

apps/tup-cms/src/apps/portal/decorators.py
Our auth redirect decorator was using `request.path` to construct redirect paths, which ignores query strings. Since users might be following a link that includes a query string, the query should get passed along when the user is redirected after authenticating.
1. Navigate to http://localhost:8000/portal/projects?show=inactive in an incognito/unauthenticated session. After logging in you should be looking at _inactive_ projects instead of the active listing.
=> bug/TUP-572: Fix- Auth redirect ignores query strings

apps/tup-cms/Dockerfile, apps/tup-cms/docker-compose.dev.yml, apps/tup-cms/src/apps/user_news/cms_plugins.py, apps/tup-cms/src/taccsite_cms/urls_custom.py
Switch to a base CMS image running Django 4.2 and update imports.
- [TUP-454](https://jira.tacc.utexas.edu/browse/TUP-454)
- requires https://github.com/TACC/Core-CMS/pull/707
1. Run `docker volume rm tup-cms_tup_cms_postgres_data` to remove data created using Postgres v10
2. Spin up the site/portal as normal and run migrations.
=> Task/TUP-454: Upgrade to Django v4.2

apps/tup-cms/src/apps/portal/backend.py
Add a timeout to the backend request made during authentication. Add more generic exception handling so that if TUP-services is unavailable for some reason, the site is still accessible.
- [TUP-602](https://jira.tacc.utexas.edu/browse/TUP-602)
1. In the `main` branch, set TUP_SERVICES_URL in the config to something that doesn't exist. Confirm the existing behavior, which is that failure to connect to tup-services will prevent the entire site from rendering.
2. Check out the PR branch and do the same thing. You should see the site render but be logged out if you were logged in before.
=> Task/TUP-602: Improve exception handling in auth backend

apps/tup-ui/src/pages/Projects/Projects.tsx, libs/core-components/src/lib/Button/Button.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateModal.tsx, libs/tup-components/src/tickets/Tickets.tsx
All header actions are now small. Also, small primary buttons are allowed.
- [TUP-559 comment (see "1.")](https://jira.tacc.utexas.edu/browse/TUP-599?focusedId=28380&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28380)
- allow small primary`<Button>`s
- header actions buttons are now all small
- allow primary tickets table button (even if not used)
1. Load all sections.
2. Verify all header action buttons are small.
| dashboard | projects | tickets |
| - | - | - |
| ![dashboard](https://github.com/TACC/tup-ui/assets/62723358/fc6302b6-8062-42d7-b320-6662f0fc5fb3) | ![projects](https://github.com/TACC/tup-ui/assets/62723358/884bc870-1695-4abf-9e14-fa9ab54c49ea) | ![tickets](https://github.com/TACC/tup-ui/assets/62723358/b58d603c-8d12-4e09-b72a-887d6780d5d4) |
=> feat: small header action buttons & allow small primary buttons

apps/tup-ui/src/main.global.css, libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx, libs/tup-components/src/tickets/Tickets.module.css
Fix inconsistent header spacing.
- [TUP-599 comment (see "3.")](https://jira.tacc.utexas.edu/browse/TUP-599?focusedId=28380&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28380)
- **fixed** `--global-space--section` not auto-updating
- **removed** extra heading space on `ManageAccount`
- **changed** `ManageAccount` to use `<SectionHeader>`
1. Open each section except Dashboard.
2. Verify same header spacing (above, beside) on all sections.
| sections |
| - |
| ![proj alloc](https://github.com/TACC/tup-ui/assets/62723358/8fe04a4b-b0ec-4135-aea7-b1199c1f8091) |
| ![proj](https://github.com/TACC/tup-ui/assets/62723358/0fba8ebc-4ec3-488b-9f6a-a101b8160b58) |
| ![tickets](https://github.com/TACC/tup-ui/assets/62723358/acbde390-105b-4130-953c-5f315f888f2f) |
| …
=> fix: ManageAccount header non-standard spacing

apps/tup-ui/src/pages/Projects/Projects.tsx, libs/core-components/src/lib/Button/Button.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateModal.tsx, libs/tup-components/src/tickets/Tickets.tsx
All header actions are now small. Also, small primary buttons are allowed.
- [TUP-615](https://jira.tacc.utexas.edu/browse/TUP-615)
- allow small primary`<Button>`s
- header actions buttons are now all small
- allow primary tickets table button (even if not used)
1. Load all sections.
2. Verify all header action buttons are small.
| dashboard | projects | tickets |
| - | - | - |
| ![dashboard](https://github.com/TACC/tup-ui/assets/62723358/fc6302b6-8062-42d7-b320-6662f0fc5fb3) | ![projects](https://github.com/TACC/tup-ui/assets/62723358/884bc870-1695-4abf-9e14-fa9ab54c49ea) | ![tickets](https://github.com/TACC/tup-ui/assets/62723358/b58d603c-8d12-4e09-b72a-887d6780d5d4) |
=> feat: tup-615 small header buttons

libs/tup-components/src/accounts/ManageAccount.module.css
Reduce size of icon in My Account section header.
<sub>Also, remove horizontal padding that is not in the [design](https://xd.adobe.com/view/cc3dc245-2792-4e10-bdc1-50d2a7d32979-996e/).</sub>
- [TUP-615](https://jira.tacc.utexas.edu/browse/TUP-615)
- **removed** horizontal padding
- **changed** icon styles
1. Open http://localhost:8000/portal/account.
2. Verify user icon in header is smaller and vertically-centered-ish with header text.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/25ead2a5-2f0c-4a3b-b865-05a827e03478) | ![after](https://github.com/TACC/tup-ui/assets/62723358/cf568c1c-ae2c-460c-a584-c1ac834b7e05) |
=> feat: tup-615 my account header

apps/tup-ui/src/main.global.css, libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx, libs/tup-components/src/tickets/Tickets.module.css
Fix inconsistent header spacing.
- [TUP-615](https://jira.tacc.utexas.edu/browse/TUP-615)
- **fixed** `--global-space--section` not auto-updating
- **removed** extra heading space on `ManageAccount`
- **changed** `ManageAccount` to use `<SectionHeader>`
1. Open each section except Dashboard.
2. Verify same header spacing (above, beside) on all sections.
| sections |
| - |
| ![proj alloc](https://github.com/TACC/tup-ui/assets/62723358/8fe04a4b-b0ec-4135-aea7-b1199c1f8091) |
| ![proj](https://github.com/TACC/tup-ui/assets/62723358/0fba8ebc-4ec3-488b-9f6a-a101b8160b58) |
| ![tickets](https://github.com/TACC/tup-ui/assets/62723358/acbde390-105b-4130-953c-5f315f888f2f) |
| ![system](https://github.com/TACC/tup-ui/assets/62723358/1590f143-9659-433a-9615-858e7a08afa9) |
| …
=> fix: inconsistent header spacing

apps/tup-ui/src/pages/Dashboard/Dashboard.module.css
Remove excess space above Dashboard header text.
- [TUP-599 comment (see "4.")](https://jira.tacc.utexas.edu/browse/TUP-599?focusedId=28380&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28380)
- **added** css to shrink header
1. Open Dashboard.
2. Make window wide (≥1200px) and tall (≥980px).
3. Verify "Dashboard" header text only has 15px of space above it.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/f69c469d-8288-4f62-84ba-ba347e237fdb) | ![after](https://github.com/TACC/tup-ui/assets/62723358/5ebb5866-de31-4981-b500-7da9a55b6338) |
<details>
</details>
=> fix: tup-615 flexible space above dashboard header

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-button.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/generics/attributes.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-core-styles.css, apps/tup-ui/src/main.global.for-core-styles.css
Migrate generics/attributes to core-styles
- [TUP-624](https://jira.tacc.utexas.edu/browse/TUP-624)
https://github.com/TACC/Core-Styles/pull/244
We use data-prefix in the blog sections on the home screen and the portal screen
=> feat: tup-624: added generics/attributes to demo

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/components/django.cms.blog.app.item.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-core-cms.css
Migrated django.cms.blog.app.item to core-cms
- [TUP-630](https://jira.tacc.utexas.edu/browse/TUP-630)
- Removed css from tup-ui and migrated to core-cms
- https://github.com/TACC/Core-CMS/pull/734
https://www.tacc.utexas.edu/news/latest-news/
=> feat/tup-630: Migrate django.cms.blog.app.item

apps/tup-cms/Dockerfile
Django 4 broke our djangocms-form plugin by deprecating the `is_ajax()` method on requests. This PR pulls in a Core-CMS image with an updated dependency.
=> Hotfix: Pull in djangocms-form fix for export bug

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/components/django.cms.picture.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-core-cms.css
Migrated django.cms.picture.css to core-cms
- [TUP-632](https://jira.tacc.utexas.edu/browse/TUP-632)
- Removed css from tup-ui and migrated to core-cms
- https://github.com/TACC/Core-CMS/pull/736
- https://www.tacc.utexas.edu/education/k-12-students/high-school-camps/gencyber-level-up/
- https://matcssi.tacc.utexas.edu/
=> feat/tup-632: Migrate django.cms.picture.css to core-cms

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-card--frontera-about-page.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-core-styles.css
This attribute is already in core-styles. Deleting from tup-ui repo.
- [TUP-618](https://jira.tacc.utexas.edu/browse/TUP-618)
- [core-styles, font-weight](https://github.com/TACC/Core-Styles/blob/b20884a012e50bc33c79aa077a3824ca172ba1ab/src/lib/_imports/components/c-card--frontera-about-page.css#L29)
This attribute is already in core-styles. Deleting from tup-ui repo.
=> feat/tup-618: c-card-frontera-page migration

apps/tup-cms/Dockerfile
Fix the PR reference for CMS image used.
- reference https://github.com/TACC/Core-CMS/pull/735
- **not** https://github.com/TACC/Core-CMS/pull/736
- **changed** comment
N/A
=> chore(tup-cms): fix image PR reference

apps/tup-cms/src/apps/portal/backend.py, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx, libs/tup-hooks/src/auth/useAuth.ts, libs/tup-hooks/src/requests.ts
Detect authentication timeouts and show an error message.
- [TUP-641](https://jira.tacc.utexas.edu/browse/TUP-641)
- Add an optional timeout to usePost.
- Detect auth timeouts within `LoginComponent` and show an error message instead of spinning forever.
- Bump internal timeouts to 15s.
=> Bug/TUP-641: Detect authentication timeouts and show an error message

apps/tup-cms/src/apps/user_news/templates/user_news/includes/read_item.html, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news--list.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-update.css
- Don't let update pill be so large.
- Use a pill for "Original Message".
- Don't add margin-left on pills on an update page.
None
1. Open https://www.tacc.utexas.edu/news/user-updates/107489/.
2. Verify pill is not so big.
3. Verify "Original Message" text is in a gray pill and same size as update pill.
4. ❗️ Verify, on an update **page**, "Update" and "Original Message" pills do **not** have `margin-left`.
5. ❗️ Verify, on an update **list**, "Update" **does** have `margin-left`.
| - | - |
| <img width="554" alt="before" src="https://github.com/TACC/tup-ui/assets/62723358/d354e134-acf4-45a8-a1d2-d068c3fc1a8c"> | <img width="554" alt="after" src="https://github.com/TACC/tup-ui/assets/62723358/e1c7df34-866f-46ea-88ca-36c66a1de4cb"> |
| - | - |
| <img …
=> hotfix: update pills too large or missing

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-core-styles.css
Deleting c-card and c-content-block imports
- [TUP-640](https://jira.tacc.utexas.edu/browse/TUP-640)
- Deleting imports from for-core-styles
- Make sure items deleted are imported from core-styles
=> feat/tup-640 Delete c-card and c-content-block imports

apps/tup-cms/src/taccsite_cms/templates/snippets/css-spacing-fixes.html
Save a snippet https://tacc.utexas.edu/admin/djangocms_snippet/snippet/104/change/.
None.
- **added** comments
- **added** [Stampede2 page](https://tacc.utexas.edu/systems/stampede2/) use case
N/A. Just saving code so it is in version control. Snippet is still in use.
| no excess space |
| - |
| <img width="705" alt="Screenshot 2023-10-18 at 4 28 02 PM" src="https://github.com/TACC/tup-ui/assets/62723358/5b8bd1f1-4038-4047-8c29-172283fc6ba6"> |
=> chore: save snippet "css-spacing-fixes"

apps/tup-ui/src/pages/Projects/Projects.tsx, libs/core-components/src/lib/SectionHeader/SectionHeader.jsx, libs/tup-components/src/projects/header/ProjectHeader/ProjectHeader.tsx, libs/tup-components/src/system-status/details/SystemStatusHeader.tsx
Do **not** nest `<header>` tags.
- [TUP-612](https://jira.tacc.utexas.edu/browse/TUP-612)
1. Open each section.
2. Inspect elements of the section header.
3. Verify only one `<header>` tag is used for the section header.
| | before | after |
| - | - | - |
| Projects | ![proj alloc - before](https://github.com/TACC/tup-ui/assets/62723358/34e7c0c5-282f-4a09-81cc-d648346ef668) |  ![proj alloc - after](https://github.com/TACC/tup-ui/assets/62723358/13b1d90e-e56c-4d58-8296-bcba769630d9)
| Project | ![project - before](https://github.com/TACC/tup-ui/assets/62723358/2b868f7d-d426-4db6-85c1-55c9669d4570) | ![project - after](https://github.com/TACC/tup-ui/assets/62723358/c814e2e7-61c5-43ff-a286-cdac77cd33bb) |
| System | ![sys status - before](https://github.com/TACC/tup-ui/assets/62723358/8959476 …
=> feat: tup-612 isNestedHeader prop in <SectionHeader>

apps/tup-cms/src/taccsite_cms/templates/snippets/css-banner-tacc.html, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/banner.css
Use `.u-highlight` not `.highlight`.
> **Warning**
> Merge delayed; pending https://github.com/TACC/Core-Styles/pull/261.
> **Important**
> After deploy:
> 1. Replace use of `highlight` class with `u-highlight` in snippet.
> 2. Replace use of `highlight` class with `u-highlight` in markup.
> 3. Test again.
> 4. Publish
>
> <details><summary>screenshot guides</summary>
>
> | | Before | After |
> | - | - | - |
> | markup | ![markup BEFORE](https://github.com/TACC/tup-ui/assets/62723358/f2ad24e6-21f0-4ceb-8425-98688a11bb3b) | ![markup AFTER](https://github.com/TACC/tup-ui/assets/62723358/b7f11284-25b7-4db8-8f6b-cd7880f37a48) |
> | snippet | ![snippet BEFORE](https://github.com/TACC/tup-ui/assets/62723358/731af865-4b79-416f-bbc4-e142703ed381) | ![snippet …
=> feat: tup 648 do not use plain highlight class

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css
Quick Fix: On production site, social media icons overlap the branding icons on footer.
- [TUP-655](https://jira.tacc.utexas.edu/browse/TUP-655)
- Added style to the `a` tag of logo branding instead of to the `p` tag
1. https://www.tacc.utexas.edu/
Scroll down to footer, expand window (if not on wide screen) and make sure icons don't overlap.
| - | - |
| <img width="2560" alt="Screenshot 2023-11-17 at 5 56 49 PM" src="https://github.com/TACC/tup-ui/assets/63771558/c395b0ae-5785-43c8-ba5d-2c0956bbee35"> | <img width="2560" alt="Screenshot 2023-11-17 at 5 59 52 PM" src="https://github.com/TACC/tup-ui/assets/63771558/1324da96-5ab3-415b-9aba-772fbf989324"> Not sure the max-height is necessary. @wesleyboar please advise. |
=> bug/tup-655 Fix footer social icon overlap

apps/tup-ui/src/main.global.css, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Load `c-form--login` from Core-Styles.
- [TUP-654](https://jira.tacc.utexas.edu/browse/TUP-654)
- **added** `c-form` and `c-form--login` classes
- **loaded** `c-form--login.css`
1. Login login form.
2. Verify form fields stretch to fill content area.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/0a92abbd-cf7c-44ed-9631-89dd6fe56581) | ![after](https://github.com/TACC/tup-ui/assets/62723358/d572049b-0baa-44aa-b216-030bd17e54df) |
There are many stylesheets and styles that can be removed since Core-Styles v2.21. Some of those removals will remove redundant styles in the login form. I will do this clean up separately, so that this PR remains solely a bug fix.
=> fix: tup-654 use c-form--login from core-styles

apps/tup-ui/src/main.global.css, libs/tup-components/src/auth/LoginComponent/LoginComponent.module.css, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Delete CSS module styles that mimic Core-Styles.
<details>
- Some Core-Styles CSS was added after TUP login form was developed.
- Now that it is available, TUP login form can use it. Less module CSS!
</details>
- [TUP-463](https://jira.tacc.utexas.edu/browse/TUP-463)
- **removes** `LoginComponent.module.css` styles that are redundant
- **changes** `<LoginComponent>` to rely mostly on Core-Styles
1. Open login form.
2. Verify form styles match production.
3. Force error to appear.
4. Verify form styles match production.
5. Resize window.
6. Verify form styles match production.
| before | after | prod |
| - | - | - |
| ![login form BEFORE](https://github.com/TACC/tup-ui/assets/62723358/9c082dbf-950e-4005-a046-5f735e782976) | ![login form …
=> enhance: tup-463 login component should use core-styles

apps/tup-ui/src/main.global.css, libs/core-components/src/lib/TextCopyField/TextCopyField.module.css
Show the invisible pipe between header links in MFA section.
<details><summary><strong>Details</strong></summary>
On the first link (the `<button>`), multiple `overflow: hidden`'s were overriding the `overflow: visible` from `c-nav`.
<details>
1. From `TextCopyField.module.css` via `c-button.css`:
1. The `x-truncate`'s `overflow: hidden` overwrote `overflow: visible`.
2. It should be the other way around.
3. Composing from `c-button.css` from `dist/` includes entire file into global scope.
2. From `main.global.css` via `c-form--login.css`:
1. The `x-truncate`'s `overflow: hidden` overwrote `overflow: visible`.
2. It should be the other way around.
3. Importing `c-form--login.css` without layer gave it precedence.
</details>
1. Compose from `/src`, to allow CSS pre-processing to get only …
=> hotfix: tup-654 mfa c nav pipe not showing

libs/core-components/src/lib/Icon/Icon.css, libs/core-components/src/lib/Icon/Icon.tsx
<details><summary>Remove redundant import of <code>cortal.icon.css</code>.</summary>
Redundant because:
1. [Portal app imports `core-styles.portal.css`.](https://github.com/TACC/tup-ui/blob/v1.1.2/apps/tup-cms/src/apps/portal/templates/portal/assets.html#L6)
2. [`core-styles.portal.css` already imports `cortal.icon.css`.](https://github.com/TACC/Core-Styles/blob/v2.21.1/src/lib/_imports/core-styles.portal.css#L27)
3. [`Icon.tsx` uses global `icon` classes.](https://github.com/TACC/tup-ui/blob/chore/remove-unnecessary-import/libs/core-components/src/lib/Icon/Icon.tsx#L20)
</details>
It caused duplicate CSS which had greater precedence than the original.
- [TUP-657](https://jira.tacc.utexas.edu/browse/TUP-657)
- **removed** import of `cortal.icon.css`
1. Open portal.
2. Verify icons still …
=> fix: tup-657 icons too small / redundant cortal.icon.css import

apps/tup-ui/src/main.global.css
Fix size of login form title "Log in" (was too small).
- [TUP-658](https://jira.tacc.utexas.edu/browse/TUP-658)
- caused by #379
- **moved** heading element styles into `base` layer
1. Open login form.
2. Verify "Log in" text is large, not small.
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/4f5cc471-0fae-4fbf-96bd-1b54fcd83fc1) | ![after](https://github.com/TACC/tup-ui/assets/62723358/d9f35251-f5c8-49c7-b82f-aa8f2ebba5b4) |
These heading styles might belong in Core-Styles anyway... so I added a comment suggesting that.
=> hotfix: tup-658 login form title too small

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-cms/trumps/search-elements.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css, package-lock.json, package.json
Fix miscellaneous bugs in #344.
- fixes #344
- coupled with https://github.com/TACC/Core-CMS/pull/753
- Search results order dropdown is still white.
- Footer buttons match production (or look better).
| test | screenshot |
| - | - |
| search | ![search](https://github.com/TACC/tup-ui/assets/62723358/bafbad77-ed54-4e2e-8790-d74cfbf818cc) |
| footer buttons | ![before](https://github.com/TACC/tup-ui/assets/62723358/0f769433-7c71-4ff8-8b7c-82a3f93a9f22) / ![after](https://github.com/TACC/tup-ui/assets/62723358/4ee78494-3891-4127-8c4e-0df41a2cbd22)
=> feat: tup-463 migrate css to core - misc bugs

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css
Make footer button small 10px. 
_Note:_ There is a comment in the code to remove small altogether. Didn't want to do this (know how to do this) until talking to @wesleyboar. 
- [TUP-580](https://jira.tacc.utexas.edu/browse/TUP-580)
- Adds 10px to the small button in the footer
1. Run tup-ui and check button size
<details>
<summary>Previous Solution</summary>
| ~~10px small button footer~~ Previous solution |
| - |
| <img width="1680" alt="Screenshot 2023-12-04 at 5 06 58 PM" src="https://github.com/TACC/tup-ui/assets/63771558/2d72158d-e6d2-4867-8d46-68af7c776376"> | 
</details>
<details>
<summary>New Solution</summary>
| 10px small button footer ( `a` tag parent) |
| - |
| <img width="1680" alt="Screenshot 2023-12-04 at 5 06 58 PM" …
=> sub-task/tup-580 Make footer button small 10px

apps/tup-cms/src/apps/portal/apps.py, apps/tup-cms/src/taccsite_cms/secrets.sample.py, apps/tup-cms/src/taccsite_cms/settings_custom.py
Catch form submission events and send users an email to confirm the submission.
- [TUP-528](https://tacc-main.atlassian.net/browse/TUP-528)
1. Submit a form from the TACC website (excluding the ticket form-- tickets already notify users through RT)
2. Check that you receive an email confirmation at the address you entered.
=> task/TUP-528: send an email when users submit a form

apps/tup-cms/src/apps/portal/apps.py
Avoid 500 error on a form that does not have `email` field, by only trying to send confirmation email if there is an `email` field.
- [TUP-675](https://tacc-main.atlassian.net/browse/TUP-675)
- fixes #392
- **added** condition for sending confirmation e-mail
1. Open old [/about/tours/request/](https://dev.tup.tacc.utexas.edu/about/tours/request/) or create a simple form.
2. Verify form does **not** have a `name="email"` field.
3. Submit form.
4. Verify form submits without 500 error.
1. Open old [/about/help-not-via-rt/](https://dev.tup.tacc.utexas.edu/about/help-not-via-rt/) or create a simple form.
2. Verify form **does** have a `name="email-address"` field.
3. Submit form.
4. Verify form submits without 500 error.
| field (`email-address`) | submit (success) |
| - | - |
| <img …
=> fix: tup-675 submit form without email gives 500

apps/tup-cms/src/taccsite_cms/settings_custom.py
Update settings to cache-bust staticfiles. Requires server restart after `collectstatic` runs (via post-deploy hook run by Watchtower).
=> Add cache busting for staticfiles

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css
The logos--branding wasn't showing on the footer in mobile view or on Safari.
- [TUP-670](https://tacc-main.atlassian.net/browse/TUP-670)
Removed a conflicting min-height style that for some reason wasn't an issue in Chrome
1. Check the branding on Safari and Safari mobile(?)
2. Check other browsers
| - | - |
| <img width="1680" alt="Screenshot 2023-12-21 at 8 10 02 PM" src="https://github.com/TACC/tup-ui/assets/63771558/99ee17b5-6da8-489f-9905-710fc849f12c"> | <img width="1530" alt="Screenshot 2023-12-21 at 8 51 40 PM" src="https://github.com/TACC/tup-ui/assets/63771558/9b90f2b0-afc5-40ea-8e58-58a363e27e21"> |
=> task/tup-670 Footer branding visible on mobile and safari

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-feed-list.css
Makes a slight adjustment for the last-child `a` tag to be 14px same as above links
- [TUP-672](https://tacc-main.atlassian.net/browse/TUP-672)
1. Gets rid of duplicate `.c-feed-list > a:last-child` selector
2. Adjusts the size of the `.c-feed-list > a:last-child` element
1. View the last `a` tag of the `.c-feed-list` element. Make sure the buttons are not 14px, but the last `a` tag is.
| Before |
| --- |
| <img width="1603" alt="Screenshot 2024-01-02 at 5 28 28 PM" src="https://github.com/TACC/tup-ui/assets/63771558/a24693a5-f084-4bbc-9127-d246c071d5c2"> | 
| <img width="1521" alt="Screenshot 2024-01-02 at 5 28 36 PM" src="https://github.com/TACC/tup-ui/assets/63771558/15b7ddfd-d9ea-4250-892f-75e3a7ffaa29"> | 
| <img width="1459" alt="Screenshot 2024-01-02 at 5 28 44 PM" …
=> task/tup-672 adjusts last c-feed-list font-size

README.md, apps/tup-cms/Dockerfile, apps/tup-cms/README.md, apps/tup-cms/src/taccsite_cms/settings_custom.py, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news--list.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news--read.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-news.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/elements/mailto-link.css, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/tup-cms.for-tup-cms.css, libs/core-components/src/lib/TextCopyField/TextCopyField.module.css, package-lock.json, package.json
Edit CSS so that Django and Vite do not use it unexpectedly.
- [TUP-677](https://tacc-main.atlassian.net/browse/TUP-677)
<details><summary>Pull Requests</summary>
- https://github.com/TACC/tup-ui/pull/400 requires:
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS/pull/780 requires:
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS-Resources/pull/197
</details>
- **refactored** comments that suggest to `@import` code
- **removed** unnecessary CSS `composes`
- **refactored** absolute `/static` paths to be relative
- **changed** core-cms & core-styles version
- **added** `STORAGES` setting to "fix a cache problem"
0. **Uncertain.** See https://github.com/TACC/tup-ui/pull/398.
1. Verify `TextCopyField` button UI and UX is …
=> feat: tup-677 css/django/vite interoperability

apps/tup-cms/Dockerfile
Update CMS image to numbered release just after https://github.com/TACC/Core-CMS/pull/787 and https://github.com/TACC/tup-ui/pull/409 which just updated the CMS image.
- formalizes https://github.com/TACC/Core-CMS/pull/787
- formalizes https://github.com/TACC/tup-ui/pull/409
- **changed** image of Core-CMS that tup-cms uses
N/A
=> chore: cms v4.5.0

README.md
Removed copy-pasta from README's `collectstatic` command.
=> docs(README): remove duplicate code from a command

.dockerignore, apps/tup-cms/.gitignore, apps/tup-cms/docker-compose.dev.yml
Support syncing host's CMS `…/data/` and `…/media/` directories into container.
- fixes local CMS build failure (@R-Tomas-Gonzalez, @wesleyboar)
- needed since merge to `main` of https://github.com/TACC/tup-ui/pulls/409
- **added** sync of CMS `media/` and `data/` folders
- **added** ignore of CMS `media/` and `data/` folders
<details open><summary>Via Existing Repo Clone</summary>
1. stop running containers
1. remove global `.gitignore` entries for CMS `data/` and `media/`
1. checkout this branch
1. verify `apps/tup-cms/src/data` is present but ignored
1. verify `apps/tup-cms/src/media` is present but ignored
1. `npm ci`
1. `npx nx build tup-cms`
1. `npx nx serve tup-cms`
</details>
<details><summary>Via New Repo Clone</summary>
1. stop running containers
1. remove global `.gitignore` …
=> fix: support local cms data and media clones

libs/tup-components/src/projects/users/UserList/ManageTeam.tsx
Update Manage Team link to fix deprecated ACCESS url
=> Chore: update Manage Team link to fix deprecated ACCESS url

libs/tup-components/src/mfa/MfaUnpairingView.tsx
If an unpairing code is provided via query param, show the user a confirmation message and a link to TUP-services to finalize unpairing.
- [TUP-698](https://tacc-main.atlassian.net/browse/TUP-698)
=> bug/TUP-698: Confirm MFA unapairing on the portal instead of through TUP-services.

libs/core-components/src/lib/SectionHeader/SectionHeader.jsx, libs/core-components/src/lib/SectionHeader/SectionHeader.module.css, libs/tup-components/src/news/UserNews.tsx
Adds in a manage button to the dashboard.
- [TUP-696](https://tacc-main.atlassian.net/browse/TUP-696)
Adds in a manage button to the dashboard using the `nav` element. Adds in a manage component to the UserNews file.
1. Check http://localhost:8000/portal/dashboard for the manage button and test it's navigation.
| Links that are piped |
| --- |
| <img width="597" alt="Screenshot 2024-02-06 at 9 40 48 PM" src="https://github.com/TACC/tup-ui/assets/63771558/6e33015f-7527-4543-98b8-f2df1f075497"> |
| UI with console |
| --- |
| <img width="1505" alt="Screenshot 2024-02-06 at 9 41 33 PM" src="https://github.com/TACC/tup-ui/assets/63771558/2ee7b440-542a-4308-b422-57a9f987c703"> |
=> sub-task/tup-696 Adds in manage button to dashboard

apps/tup-cms/src/apps/staff_profile/forms.py, apps/tup-cms/src/apps/staff_profile/templates/staff_profile/includes/display_name.html, apps/tup-cms/src/apps/staff_profile/templatetags/post_nomials.py, apps/tup-cms/src/taccsite_cms/settings_custom.py
This adds a post-nomial exclusion list so it does not appear on staff directories. 
- [CMD-80](https://tacc-main.atlassian.net/browse/CMD-80)
1. Adds in logic to watch for post-nomials.
2. Constant might need to be moved around in the settings file
1. I used Rad.Buk. as a reference for this. Go [here](http://localhost:8000/about/staff-directory/)
2. Choose Rad.Buk. 
3. Change his post-nomials to something in the list that I added to settings. 
4. Watch for the appearance and disappearance of the comma before the post-nomial
| In exclusion list |
| --- |
| <img width="81" alt="Screenshot 2024-02-06 at 4 27 15 PM" src="https://github.com/TACC/tup-ui/assets/63771558/815cf07a-1785-4acd-92a1-220c5d856369"> |
| <img width="66" alt="Screenshot 2024-02-06 at 4 28 50 PM" …
=> CMD-80 Adds post-nomial exclusions

apps/tup-cms/src/taccsite_cms/settings_custom.py, apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css
Support changes to NSF branding (per new guidelines and CMD decisions).
- [CMD-82](https://tacc-main.atlassian.net/browse/CMD-82)
- (in repo code) **removed** `NSF_BRANDING`
- (in repo code) **changed** CSS `padding-…` value
- _(in CMS structure) **changed** footer layout_
| Local | Dev ([deployed](https://jenkins01.tacc.utexas.edu/job/tup-cms-deploy/180/)) | Prod |
| - | - | - |
| replace CMS Footer columns in homepage [import](https://github.com/django-cms/djangocms-transfer/blob/1.0.0/README.rst#django-cms-transfer)ing this [export](https://github.com/TACC/tup-ui/files/14273731/cmd-82.cms.footer.plugins.json) | https://dev.tup.tacc.utexas.edu/ (no snippet) | https://tacc.utexas.edu/homepage-banner-2024-02/ (uses [snippet #144](https://tacc.utexas.edu/admin/djangocms_snippet/snippet/144/ …
=> feat: cmd-82 update nsf branding

apps/tup-cms/src/taccsite_cms/settings_custom.py
In CMS settings, use comments/organization like Core-CMS.
_This is an innocuous piece of settings clean up across repos._
- [WI-110](https://tacc-main.atlassian.net/browse/WI-110)
- **renamed** some CMS setting sections (comments)
- **moved** some CMS settings (no change)
N/A
=> style: WI-110 CMS settings naming and order

apps/tup-cms/src/taccsite_cms/templates/snippets/logos-social-media.html
Saving a snippet, because it has unique code.
- manual version of https://github.com/TACC/Core-CMS/blob/v4.8.0/taccsite_cms/templates/share_on_social.html output + new BlueSky item (not in Core-CMS)
- **added** CMS template
1. Verify code is saved in snippet.
2. Verify social media icons include BlueSky.
3. Verify social media icons are responsive.
> [!IMPORTANT]
> Log in to Portal before clicking link.
| Site | Log In | Snippet |
| - | - | - |
| Prod | [`/login`](https://tacc.utexas.edu/login) | [snippet #100](https://tacc.utexas.edu/admin/djangocms_snippet/snippet/100/change/) |
| Dev | [`/login`](https://dev.tup.tacc.utexas.edu/login) | [snippet #100](https://dev.tup.tacc.utexas.edu/admin/djangocms_snippet/snippet/100/change/) |
| 1. & 2. |
| - |
| <img width="299" alt="footer …
=> chore: save logos snippet, it has new unique code

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-feed-list.css
In `c-feed-list`:
- Add support for `<time>` wrapped in `<p>`.
- Retain support for `<time>` **not** wrapped in `<p>`.
| Before Editing Text Plugin Instances | After Editing Text Plugin Instances |
| - | - |
| The `<time>` is **not** wrapped in a `<p>` tag. Nor is "See all …" link. | The `<time>` **is** wrapped in a `<p>` tag. So is "See all …" link. |
| <img width="531" alt="after edit" src="https://github.com/TACC/tup-ui/assets/62723358/f00eb900-f2f1-482e-80ef-13ad18d05b29"> | <img width="531" alt="beofre edit" src="https://github.com/TACC/tup-ui/assets/62723358/7a6a4dd1-eb13-48fa-9d16-6a467b0def06"> |
<details><summary>Video</summary>
https://github.com/TACC/tup-ui/assets/62723358/9fe25b2d-4f3b-4503-ab6d-dc8e50b4d695
</details> 
- fix side effect of TACC/tup-ui#412
<sup> A `<p>` is …
=> hotfix: c-feed-list must support `<p><time/></p>`

libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx
Stacks content in the Account Management screen when the narrow breakpoint is reached.
- [TUP-537 (Parent Ticket)](https://tacc-main.atlassian.net/browse/TUP-537)
- [TUP-689](https://tacc-main.atlassian.net/browse/TUP-689)
- [TUP-688](https://tacc-main.atlassian.net/browse/TUP-688)
- [TUP-690](https://tacc-main.atlassian.net/browse/TUP-690)
Stacks content in the Account Management screen when the narrow breakpoint is reached.
1. http://localhost:8000/portal/account
2. Make screen smaller and wider to see the MFA be under the main content on left
| - | - |
| <img width="587" alt="Screenshot 2024-02-19 at 1 06 07 PM" src="https://github.com/TACC/tup-ui/assets/63771558/bc2bd818-8000-4884-a54f-1882c39742d8"> | <img width="586" alt="Screenshot 2024-02-19 at 1 06 30 PM" …
=> TUP-689  On Small Screen, Stack Manage Account Blocks into 1 Column

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-tup-cms/components/c-footer.css
Revert the CSS change that supported a footer layout change on production that I was just told to undo.
> [!IMPORTANT]
> This change is coupled to a bunch of bootstrap class changes I made to footer columns via the CMS admin. I did not track those changes. I am sorry.
- [CMD-82](https://tacc-main.atlassian.net/browse/CMD-82)
- revert CSS change from #425
- **changed** `padding-left` back to `padding-right`
**Fast Way**: Verify that prod looks as it was before #425 now… (I removed the snippet that replicated the #425 change on prod.)
https://tacc.utexas.edu/
=> hotfix: revert c-footer layout change

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Add error styling to tup login
- [TUP-692](https://tacc-main.atlassian.net/browse/TUP-692)
Adds `className='c-form'` to `form` element instead of `div` element to allow for styling to take effect.
1. http://localhost:8000/portal/login?from=/portal/account
2. Hit the submit button without entering any of the fields.
3. Make sure it pops up red
| - | - |
| <img width="650" alt="Screenshot 2024-02-21 at 5 51 49 PM" src="https://github.com/TACC/tup-ui/assets/63771558/ce30ca32-f438-4fe9-bb0c-e651d5755a45"> | <img width="639" alt="Screenshot 2024-02-21 at 5 52 36 PM" src="https://github.com/TACC/tup-ui/assets/63771558/25616adf-0950-4528-b56b-eb433e750a7a"> |
=> bug/TUP-692  TUP Login Form Error Message Unstyled

libs/tup-components/src/software/SoftwareTable.tsx, libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
Remove decommissioned systems from Help Ticket dropdown.
1. Should I remove Longhorn from [/use-tacc/software-list/](https://tacc.utexas.edu/use-tacc/software-list/) i.e. [`SoftwareTable.tsx`](https://github.com/TACC/tup-ui/blob/v1.1.6/libs/tup-components/src/software/SoftwareTable.tsx#L193) also?
- H.P. says "Yes" to removing from [Software Table](https://tacc.utexas.edu/use-tacc/software-list/) because V.T. said, "Yes" to removing it from Help Ticket. It's just an option. The data is from an API.
3. Should I remove [Longhorn and Maverick from test fixtures](https://github.com/TACC/tup-ui/blob/v1.1.6/libs/tup-testing/src/mocks/fixtures/system-status.ts#L25-L61)?
- [TUP-705](https://tacc-main.atlassian.net/browse/TUP-705)
- **removed** some `<option>`s
Skipped.
| | Before | After |
| - | …
=> feat: TUP-705 remove decomissioned systems

apps/tup-cms/src/taccsite_custom/tup_cms/static/tup_cms/css/for-core-styles/components/c-feed-list.css
Style `<time>` used (by "User Updates" via `c-feed-list`) without a `<p>`.
- fixes #427
- **added** selectors to style `<time>` **not** wrapped in `<p>`
1. Open https://dev.tup.tacc.utexas.edu/ or local clone.
2. Scroll to "User Updates".
3. Verify the `<time>` (e.g. "Published:" and "FEBRUARY 12, 2024") is orange-ish.
4. Verify the style rule that does this would also style the `<time>` were it in a `<p>` tag.
| - | - |
| <img width="350" alt="before" src="https://github.com/TACC/tup-ui/assets/62723358/923f53ae-016b-421f-a2f8-5bbff04a56b8"> | <img width="350" alt="after" src="https://github.com/TACC/tup-ui/assets/62723358/51f3ab65-bf3e-4a97-bde9-d9678d6265f9"> |
| Both Ways Work |
| - |
| <img width="1194" alt="works both ways" …
=> fix: c-feed-list must still support `<time/>`

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/templates/assets_custom.html, package-lock.json, package.json
Update Core-CMS & Core-Styles to latest versions.
- [TUP-702]
- [TUP-703]
- [TUP-707]
- [DES-2697](https://tacc-main.atlassian.net/browse/DES-2697)
- [TUP-676]
- requires https://github.com/TACC/Core-CMS/pull/807
[TUP-534]: https://tacc-main.atlassian.net/browse/TUP-534 "CMS Tables on Mobile"
[TUP-702]: https://tacc-main.atlassian.net/browse/TUP-702 "New Window Links Not Accessible"
[TUP-703]: https://tacc-main.atlassian.net/browse/TUP-703 "TACC Home Banner Links Open in New Window"
[TUP-707]: https://tacc-main.atlassian.net/browse/TUP-707 "Filter News for Other Sites"
[TUP-676]: https://tacc-main.atlassian.net/browse/TUP-676 "CMD Form Error Message is Missing Padding"
[DES-2697]: https://tacc-main.atlassian.net/browse/DES-2697 "Style App Card Pattern"
- **[v4.8.3: Fix External Link …
=> feat: core-cms v4.8 & core-styles v2.25

libs/tup-components/src/accounts/ManageAccount.module.css, libs/tup-components/src/accounts/ManageAccount.tsx, libs/tup-components/src/accounts/ManageAccountMfa.tsx
Reduce complexity of TAM links UI. Add more useful context.
- [TUP-704](https://tacc-main.atlassian.net/browse/TUP-704)
- **deleted** css & markup
- **changed** css & markup
1. Visit "Manage Account" page.
2. Feel out the UI for bugs (responsiveness, spacing, font, et cetera).
3. Confirm designer approval.
| Before | Before (More) | After |
| - | - | - |
| <img width="1280" alt="before" src="https://github.com/TACC/tup-ui/assets/62723358/77c94900-5691-4206-9b7f-3c342e22612f"> | <img width="1280" alt="before - scrolled" src="https://github.com/TACC/tup-ui/assets/62723358/74f8c436-3ee0-4e18-94c7-90ecdbe3c2c8"> | <img width="1280" alt="option 4A - tweak 1" src="https://github.com/TACC/tup-ui/assets/62723358/1b73588a-6138-4403-bae0-a0415f2cce97"> |
<details><summary>Archived</summary>
| we …
=> feat: TUP-704 simplify TAM links UI

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/settings_custom.py
Set the public share platforms settings in the repo, not hidden on the server in secrets.
- requires https://github.com/TACC/Core-CMS/pull/813
- tangentially…
- [TUP-584](https://tacc-main.atlassian.net/browse/TUP-584)
- [TUP-667](https://tacc-main.atlassian.net/browse/TUP-667)
- **added** settings that were on dev server
- **changed** order of the platforms
1. Load https://dev.tacc.utexas.edu/news/.
2. Open a news article.
3. Verify share buttons are present and working in this order:
1. linkedin
2. facebook
3. email
| - | - |
| <img width="1194" alt="tup-ui 442 before" src="https://github.com/TACC/tup-ui/assets/62723358/55a1e8a7-caf0-4efd-8999-cca162c74f5b"> | <img width="1194" alt="Screenshot 2024-03-08 at 3 59 28 PM" …
=> feat: set share platforms in repo code & reorder them

apps/tup-cms/src/taccsite_cms/secrets.sample.py, apps/tup-cms/src/taccsite_cms/settings_local.sample.py
1. Do not suggest enabling SMTP in local settings/secrets. Why not?
- [We should not send e-mail from localhost.](https://tacc-main.atlassian.net/wiki/x/ZhVv)
- [Mail can be previewed in console via default Core-CMS settings.](https://github.com/TACC/Core-CMS/blob/main/taccsite_cms/_settings/email.py#L22)
3. Do offer dev URL for TUP services.
- fix recipe for trouble in #392
- **removed** secrets
- **added** settings
N/A
=> fix: sample secrets should not suggest user use smpt locally

apps/tup-cms/Dockerfile, apps/tup-cms/src/taccsite_cms/settings_custom.py
Redesign news metadata.
- [TUP-584](https://tacc-main.atlassian.net/browse/TUP-584)
- requires https://github.com/TACC/Core-CMS/pull/773
- includes #442
- re-ordered share links
- changed position of news article metadata
Deployed to [dev server](https://dev.tup.tacc.utexas.edu/news/latest-news/).
<sup>If testing locally, run `npx nx build tup-cms && npx nx serve tup-cms`.</sup>
1. Open news list.
2. Compare to production.
3. Open any news article that has an author.
4. Compare that article to production.
5. Review design UI and responsiveness and usability.
6. Verify [I got designer approval](https://tacc-team.slack.com/archives/C060NU133D5/p1710520467347929).
| - | - |
| <img width="1194" alt="page before" src="https://github.com/TACC/tup-ui/assets/62723358/aa5716d9-a5 …
=> feat: tup 584 redesign news metadata

apps/tup-cms/src/apps/portal/apps.py
Fix TUP-managed confirmation e-mails not being sent.
- [TUP-711](https://tacc-main.atlassian.net/browse/TUP-711) & [TUP-709](https://tacc-main.atlassian.net/browse/TUP-709)
- **fixed** wrong syntax within `elif` conditional
1. Test via a form that has an "Email" (`email`) field e.g.
- `/about/tours/request/`
- [`/about/help-not-via-rt/`](https://dev.tup.tacc.utexas.edu/about/help-not-via-rt/) (set recipient e-mail to your own)
2. Check whether e-mail is received.
3. Set mail program to render mail as text.
4. Check whether the received mail has excess indentation.
| to User | to TACC |
| - | - |
| <img width="705" alt="to User" src="https://github.com/TACC/tup-ui/assets/62723358/c4b568db-7031-42cd-a9ee-7d41a8f00666"> | <img width="705" alt="to TACC" …
=> fix: tup-711 confirmation e-mail not sent

apps/tup-cms/src/apps/portal/apps.py
Fix a misspelling in the confirmation e-mail.
This e-mail is not even being sent. The fix for that is https://github.com/TACC/tup-ui/pull/446.
=> fix: misspelling in confirmation e-mail

libs/tup-components/src/projects/ProjectsListing/ProjectsListingAllocationTable.tsx, libs/tup-components/src/projects/details/ProjectDetails.test.tsx
Show inactive allocations on active projects.
- [TUP-713](https://tacc-main.atlassian.net/browse/TUP-713)
1. Open a project and check that the `Status` column appears in the allocations table.
=> task/TUP-713: Show inactive allocations on active projects and distinguish by 'status'

libs/tup-components/src/auth/LoginComponent/LoginComponent.spec.tsx, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Update TACC login form to display "Username" not "User Name".
- noticed during [TUP-712](https://tacc-main.atlassian.net/browse/TUP-712)
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/01b08eb6-af15-4fba-a51c-834523d6981b) | ![after](https://github.com/TACC/tup-ui/assets/62723358/a87afa82-b69b-41f3-aec6-6726f9cc9dc9) |
=> fix: tup-712 "Username" not "User Name"

libs/tup-components/src/mfa/MfaQRPanel.tsx
Remove unused property (not previously noticed, cuz core-components TypeScript was not checked).
- [TUP-700](https://tacc-main.atlassian.net/browse/TUP-700)
- fixes bugs in #463
- **fixed** dependency organization
- **refactored** Formik field wrappers to work from external package
1. `npx nx build tup-ui --skip-nx-cache`
2. Verify no **errors**.
<details><summary>Before</summary>
```log
npx nx build tup-ui --skip-nx-cache
✔    1/1 dependent project tasks succeeded [0 read from cache]
Hint: you can run the command with --verbose to see the full dependent project outputs
———————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> nx run tup-ui:build:production
libs/tup-components/src/mfa/MfaQRPanel.tsx:62:15 - error TS2322: Type '{ …
```
=> fix: TUP-700 @tacc/core-components - a typescript bug

libs/core-components/README.md, libs/core-components/package.json, package-lock.json
Fix & Polish the README for @tacc/core-components.
- [TUP-700](https://tacc-main.atlassian.net/browse/TUP-700)
- **fixed** README
- **updated** README
- **updated** version
https://github.com/TACC/tup-ui/blob/docs/TUP-700-core-components-node-pkg--readme/libs/core-components/README.md
=> docs: TUP-700 @tacc/core-components - readme

libs/tup-components/src/auth/LoginComponent/LoginComponent.spec.tsx, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Update TACC login form to _synergize_ with TAM login form.
- [TUP-712](https://tacc-main.atlassian.net/browse/TUP-712)
- https://github.com/DesignSafe-CI/portal/pull/1324
- **changed** Account Help link to new login support form
- **changed** internal name of Reset Password link
1. Load login page.
2. Verify it has this text and link combo:
> Having trouble logging in?
> - [Account Help](https://accounts.tacc.utexas.edu/login_support)
> - [Forgot Password](https://accounts.tacc.utexas.edu/forgot_password)
> - [Recover Username](https://accounts.tacc.utexas.edu/forgot_username)
| - | - |
| ![before](https://github.com/TACC/tup-ui/assets/62723358/66b643db-0925-447a-b21b-888972a59043) | ![after](https://github.com/TACC/tup-ui/assets/62723358/1f91839f-bb9b-4cee-9540-ed6b9d64 …
=> feat: tup-712 login form new help links

libs/tup-components/src/news/UserNews.module.css
User News uses too small a font size. It is:
- inconsistent with the rest of the portal
- below minimum _generally-accepted_ accessible font size
- [CMD-172](https://tacc-main.atlassian.net/browse/CMD-172)
- **changed** a style
Verify font-size of User News smallest text:
1. is bigger
2. matches table cell text font size
| - | - |
| <img width="1200" alt="user news - before" src="https://github.com/TACC/tup-ui/assets/62723358/233b2646-e96d-4198-a854-423516f33dd6"> | <img width="1200" alt="user news - after" src="https://github.com/TACC/tup-ui/assets/62723358/bf44ad17-ca08-426a-916f-30845d7eb1c4"> |
=> fix: CMD-172 user news 10px font not accessible

apps/tup-cms/src/apps/portal_nav/templates/portal_nav/nav_portal.raw.html, apps/tup-cms/src/taccsite_cms/templates/snippets/logos-social-media.html
SVGs and icons are now accessible.
- [CMD-171](https://tacc-main.atlassian.net/browse/CMD-171)
- similar to https://github.com/TACC/Core-CMS/pull/845
- **added** `role` attribute and `title` tag
1. Verify markup has changed.
2. Verify affected graphics have accessible `role` and `title`.
3. Verify images still display as they had.
Skipped.
=> fix: CMD-171 svgs & icons not accessible

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Tell user if there account is suspended. Direct them to TAM.
- [RT #99514](https://consult.tacc.utexas.edu/Ticket/Display.html?id=99514)
- [Slack discussion (short-lived link)](https://tacc-team.slack.com/archives/CKB616RB8/p1722017896778129)
- **add** new error code to `<LoginError>`
1. Render the error. Options:
- Try to login with suspended account.
- Fake a `451` response from server.
- Enter bad credentials, then edit error markup.
2. Verify login form shows error about account suspension.
3. Verify error has working link to https://accounts.tacc.utexas.edu/login_support.
| balanced (a290672) |
| - |
| <img width="980" alt="RT 99514 Solution Proposal - Balanced" src="https://github.com/user-attachments/assets/0b8f93a7-d97d-4e61-bd45-be433f99ebea"> | …
=> fix: RT-99514 unique state for suspended user

apps/tup-cms/src/taccsite_cms/templates/snippets/js-prevent-ugly-urls.html
Save a working snippet that reverts some Google Analytics JavaScript.
<details>Links on CMS page to subdomain are changed by Google to be functional but full of unsightly query parameters.</details>
- [TUP-715](https://tacc-main.atlassian.net/browse/TUP-715)
- **saved** snippet that I have long been using to patch the bug
1. Open [tacc.utexas.edu](http://tacc.utexas.edu/).
2. In menu, click "Use TACC" > "Documentation".
Verify URL does **not** have a string of query parameters.
3. Open https://tacc.utexas.edu/use-tacc/getting-started/.
4. On page, click "1. Create an Account" > [Create Account].
Verify URL does **not** have a string of query parameters.
<sup>To test previous behavior, comment out `<script>` in [snippet #150](https://tacc.utexas.edu/admin/djangocms_snippet/snippet/150/chang …
=> fix: tup-715 save patch fix of subdomain link ugly URLs

apps/tup-cms/src/taccsite_cms/templates/snippets/css-banner-tacc.html, apps/tup-cms/src/taccsite_cms/templates/snippets/css-global-a11y.html, apps/tup-cms/src/taccsite_cms/templates/snippets/css-homepage-2024-02.html
Save snippet that only existed in CMS content. Migrate a note to an existing snippet.
None.
- **added** `templates/css-global-a11y.html`
- **added** note to `templates/css-banner-tacc.html`
> [!NOTE]
> Not required. This change merely saves code that has been working live.
1. Open two different pages on https://tacc.utexas.edu website.
2. Make window narrow enough that mobile nav appears.
3. **Verify mobile nav button has white-gray border.**
4. Open mobile nav.
5. Focus on search field.
6. **Verify search field button has thick white border.**
| sans new snippet | with new snippet |
| - | - |
| <img width="520" alt="before snippet" src="https://github.com/TACC/tup-ui/assets/62723358/ec71ef37-92a6-45b5-82d3-db1968c6c78e"> | <img width="520" alt="after snippet" …
=> feat: save 2 css snippets

apps/tup-cms/src/apps/portal/apps.py
Use setting `DEFALT_EMAIL_FROM` instead of hard-coded `no-reply@tacc.utexas.du`.
None. Noticed while testing.
> [!TIP]
Deployed to [dev](https://dev.tup.tacc.utexas.edu) via [v1.1.11-202409-02](https://github.com/TACC/tup-ui/releases/tag/v1.1.11-202409-02).
0. Deploy to dev server.
1. Send e-mail via [Request Tour form](https://dev.tup.tacc.utexas.edu/about/tours/request/).
2. Verify response is from `no-reply@dev.tup.tacc.utexas.edu`.
3. If response is still `no-reply@tacc.utexas.edu`, check dev server settings.
=> fix: use DEFAULT_EMAIL_FROM not hard-coded e-mail

apps/tup-cms/src/apps/portal/apps.py
- Update form confirmation email with new copy from Hedda
- For tour requests, include a copy of the full form submission for people's records.
- [WI-154](https://tacc-main.atlassian.net/browse/WI-154)
1. Submit a tour request and check that the email you receive has a copy of the submission parameters.
=> Update form confirmation email and show requested tour info

apps/tup-cms/src/taccsite_cms/templates/snippets/js-epic-data-dashboard.html
Update the EPIC tableau dashboard snippet with latest code from stakeholder.
> [!IMPORTANT]
> After deploy, consider emptying the HTML of [snippet #55](https://tacc.utexas.edu/admin/djangocms_snippet/snippet/55/change/).
- [RT #30345](https://tickets.tacc.utexas.edu/Ticket/Display.html?id=30345)
- **added** a snippet
1. Open https://dev.tup.tacc.utexas.edu/education/educators/data-dashboard/?edit
2. Test dashboard at different screen widths: <500, 500–800, 800+.
> [!CAUTION]
> Not responsive. H.P. assumed the task from me. On production. I trust her decision.
| in isolation | within tacc |
| - | - |
| <img width="1280" alt="unresponsive tableau isolated" src="https://github.com/user-attachments/assets/93c04854-43b1-40c5-afeb-2a485bf7b45e"> | <img width="1280" alt="unresponsive tableau in …
=> feat: RT 30345 new epic tableau dashboard snippet

apps/tup-cms/project.json
- Do **not** use deprecated `docker-compose `command.
- **Do** use Docker Compose v2+ command, `docker compose`.
> [!IMPORTANT]
> Command `docker-compose` **fails** in latest versions of Docker Compose.
- [WP-602](https://tacc-main.atlassian.net/browse/WP-602)
- https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
- **replaced** `docker-compose ` with `docker compose`
0. Have Docker-Compose v2 (latest or relatively new).
1. Run any `npx nx serve …` command.
2. Verify no error about `docker-compose` command.
0. Have Docker-Compose v2 (older version).
1. Run any `npx nx serve …` command.
2. Verify no error about `docker-compose` command.
Skipped.
=> fix: deprecated docker-compose command

apps/tup-cms/src/apps/portal/apps.py
Do **not** show `recaptcha_…` field and value in Tour Request response
- [WI-154](https://tacc-main.atlassian.net/browse/WI-154)
- enhances #480
- included in #483
- **added** conditional to field output
0. Have a form called "Tour Request Form".
1. Ensure form has functional ReCaptcha field.
2. Submit form.
3. Verify auto-reply does **not** show `recaptcha_…` field **nor** value.
See https://github.com/TACC/tup-ui/pull/483.
=> enhance: WI-154 do not show recaptcha data

apps/tup-cms/src/apps/portal/apps.py, apps/tup-cms/src/apps/portal/utils.py
In "Tour Request Form" response:
- **do** show field labels
<sup>which are for users</sup>
- **not** field name keys
<sup>which are for code</sup>
- [WI-154](https://tacc-main.atlassian.net/browse/WI-154)
- enhances https://github.com/TACC/tup-ui/pull/480
- includes #481
- **changed** field value name shown to user in e-mail
- **removed** recaptcha field value
0. Have a form called "Tour Request Form".
1. Submit form.
2. Verify auto-reply:
- does **not** show reCAPTCHA value
- shows "First Name" **not** `first-name`
- shows "Name of Your Organization" **not** `name-of-your-organization`
- et cetera
| - | - |
| <img width="960" alt="WI-154 Email Top (BEFORE)" src="https://github.com/user-attachments/assets/46934533-a13a-4100-b112-46425d06658f"> | <img width="960" …
=> enhance: WI-154 show field labels not keys

libs/tup-components/src/auth/LoginComponent/LoginComponent.spec.tsx, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Label "Username" also as "Username and Email".
- [internal request](https://tacc-team.slack.com/archives/CKB616RB8/p1729697761158459)
1. Run tests on tup-components. Verify LoginComponent passes.
2. Load tup-ui at login screen. Verify label is "Username and Email".
Skipped.
=> enhance(tup-comp…): username label also say email

apps/tup-cms/src/taccsite_cms/settings_custom.py
**Enable** BlueSky social media service to News share buttons.
**Enables** feature from:
- [CMD-147](https://tacc-main.atlassian.net/browse/CMD-147)
- https://github.com/TACC/Core-CMS/pull/832
1. Build/Start CMS on this branch.
<sup>Deployed to [dev](https://dev.tup.tacc.utexas.edu/news/latest-news/2024/02/01/nsf-selects-tacc-supercomputers-for-national-ai-research-resource-nairr-pilot/).</sup>
2. Create/Open a news article.
<sup>E.g. [(dev) NSF Selects TACC Supercomputers for National AI Research Resource Pilot](https://dev.tup.tacc.utexas.edu/news/latest-news/2024/02/01/nsf-selects-tacc-supercomputers-for-national-ai-research-resource-nairr-pilot/).</sup>
3. Verify BlueSky icon is present in share options.
4. Click BlueSky icon.
5. Verify new tab appears that lets user share link on …
=> feat: CMD-147 enable BlueSky share

libs/tup-components/src/software/SoftwareTable.tsx
Add "Stampede3". Add "Vista". Remove "Stampede 2".
- [TUP-731](https://tacc-main.atlassian.net/browse/TUP-731)
1. Open https://dev.tup.tacc.utexas.edu/use-tacc/software-list/.
2. Open "System" dropdown.
3. See "Stampede 3", "Vista", but not "Stampede2".
4. Select these two new options.
5. Verify table updates appropriately.
https://github.com/user-attachments/assets/865b6786-8e59-4b12-af76-4ce327f930da
=> fix: TUP-731 software table missing stampede3 & vista

apps/tup-cms/src/apps/portal/decorators.py, apps/tup-cms/src/apps/portal/views.py, libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Fix redirect for CMS pages where login is required (e.g. planned allocation form)
Testing directions: For testing purposes I've changed the "citing TACC" page to require lgin. Go to https://dev.tup.tacc.utexas.edu/about/citing-tacc/ while logged out, and check that you get redirected to the "citing tacc" page after login
=> Quick: Change login redirect param from 'from' to 'next' to match CMS config

libs/tup-components/src/auth/LoginComponent/LoginComponent.tsx
Show a message when a user's account has been deactivated:
=> Hotfix: Show message for deactivated account

apps/tup-cms/src/taccsite_cms/settings_custom.py
The updated core-cms image requires `PORTAL_SEARCH_INDEX_IS_AUTOMATIC = False` to be configured in settings, otherwise our existing haystack config isn't respected.
- required since https://github.com/TACC/Core-CMS/pull/857
=> Quick: Fix haystack error on publish

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
Add space before "(…)" in System dropdown.
_Already changed on [CMS help page](https://tacc.utexas.edu/about/help/) form._
None.
- **added** space to user-facing text
1. Open portal.
2. Begin to create ticket.
3. View "System/Resource" field options.
4. Verify open parentheses is always preceded by a space.
Skipped, because option value is just used as a string for a string:
* [portal form](https://github.com/TACC/tup-ui/blob/v1.1.13/libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx#L63)
* [cms form](https://github.com/TACC/tup-ui/blob/v1.1.13/apps/tup-cms/src/apps/portal/apps.py#L32C52-L32C66)
=> style: add space before open parens

apps/tup-cms/src/taccsite_cms/templates/snippets/css-fix-padding-on-plain-cards-with-lists-after-paragraph.html, apps/tup-cms/src/taccsite_cms/templates/snippets/css-remove-padding-between-section-h3-and-paragraph.html, apps/tup-cms/src/taccsite_cms/templates/snippets/css-spacing-fixes.html
Add 2 new snippets. Update 1 old snippet.
N/A. Just saving code that is now or has been live.
The new snippets are used on these pages (as of today):
- https://tacc.utexas.edu/education/undergraduates-graduates/reu/research-projects/
- https://tacc.utexas.edu/education/undergraduates-graduates/reu/research-projects/archive/
> [!NOTE]
> One day I'll implement a non-snippet way to add TUP-specific CSS, but not today.
> <details><summary>Ideas</summary>
>
> 1. I could load stylesheets via CMS setting `PORTAL_STYLES`; and load even more this way after enhancements from https://github.com/TACC/Core-CMS/pull/880.
> 2. I could load one stylesheet (in any manner) from a URL that is always live, never cached. CDN's appear to have those, but there is still cache; but JSDelivr's cache for such URLs …
=> chore(tup-cms): save new snippets (added today)

apps/tup-cms/src/taccsite_cms/settings_custom.py, apps/tup-cms/src/taccsite_cms/templates/bare.html
Add a CMS template to support loading TACC news HTML on other sites.
- [TUP-706](https://tacc-main.atlassian.net/browse/TUP-706)
- supports https://github.com/TACC/Core-CMS/pull/868
- **added** a template `bare.html`
- **added** `CMS_TEMPLATES` entry
1. Open https://dev.tup.tacc.utexas.edu/news/latest-news/?template=bare.html
2. Verify page loads News content but:
- no header nor footer
- no global assets (e.g. styles, scripts)
3. (Optional) Verify page template "Bare" is available to editors.
<sup>Editors should **not** use this, but it must be available to support `?template=`.</sup>
| New Feature | Regular View
| - | - |
| <img width="960" alt="dev tup news bare" src="https://github.com/user-attachments/assets/cebcec65-65fb-4cee-9893-2fc5224394ef" /> | <img width="960" alt="dev tup …
=> feat: tup-706 support news on other sites

libs/tup-components/src/tickets/TicketCreateModal/TicketCreateForm.tsx
<details><summary>The Category field in Ticket form is missing "Security Incident".</summary>
1. N.M. reported this to H.P. for CMS form.
2. I updated [CMS help page](https://tacc.utexas.edu/about/help/) form.
3. I checked this form, which is also missing it.
4. I failed to find in Git history when it was lost.
5. J.R. reveals change caused by [TUP-539](https://tacc-main.atlassian.net/browse/TUP-539).
</details>
- revert [TUP-539](https://tacc-main.atlassian.net/browse/TUP-539)
- **added** `<option>` to a form field
- **added** help text to that form field
1. Open portal.
2. Open modal to create a ticket.
3. View "Category" field.
4. Verify "Security Option" is present.
5. Verify help text is
> For issues with MFA or CoC, choose "Multi-factor Authentication" or "Other" respectively. …
=> fix: missing "Security Incident" category

libs/tup-components/src/accounts/ManageAccount.tsx
Fix a typo, "Managment" to "Management".
- originates from #431
- **added** a letter
1. Verify spelling is correct.
2. Verify no other changes.
Skipped.
=> fix: typo "Managment"

apps/tup-cms/Dockerfile
Update CMS just enough to fix error during [migration](https://github.com/TACC/Core-CMS/blob/v4.24.2/taccsite_cms/migrations/0001_add_groups.py?rgh-link-date=2025-08-12T19%3A41%3A25Z) that [has become noop](https://github.com/TACC/Core-CMS/pull/932).
- from https://github.com/TACC/Core-CMS/releases/tag/v4.23.0
- to https://github.com/TACC/Core-CMS/releases/tag/v4.28.2
- [v4.24.3](https://github.com/TACC/Core-CMS/releases/tag/v4.24.3), [v4.25.2](https://github.com/TACC/Core-CMS/releases/tag/v4.25.2): test portal nav — on CMS page, and in Portal
- [v4.25.0](https://github.com/TACC/Core-CMS/releases/tag/v4.25.0), [v4.25.1](https://github.com/TACC/Core-CMS/releases/tag/v4.25.1), [v4.26.1](https://github.com/TACC/Core-CMS/releases/tag/v4.26.1): test header UI — **font change**, otherwise zero …
=> fix: fresh CMS migrate (i.e. Core-CMS v4.24 to v4.28)
